/**
 * CrossFit WODs Library
 * 
 * Add your favorite CrossFit workouts here!
 * The AI will use these as examples when generating new workouts.
 * 
 * You can add:
 * - Famous CrossFit benchmark WODs (Fran, Murph, Grace, etc.)
 * - Your own custom WODs
 * - Competition workouts
 * - Any workout style you like
 */

export interface CrossFitWOD {
  name: string;
  type: 'AMRAP' | 'EMOM' | 'For Time' | 'Chipper' | 'Rounds' | 'Tabata' | 'Custom';
  duration?: number; // in minutes
  description: string;
  movements: string[]; // List of movements with reps
  notes?: string; // Scaling, modifications, etc.
}

export const crossfitWODs: CrossFitWOD[] = [
  // FAMOUS CROSSFIT BENCHMARK WODS
  {
    name: 'Fran',
    type: 'For Time',
    description: '21-15-9 reps for time',
    movements: [
      '21-15-9 Thrusters (43/29 kg)',
      '21-15-9 Pull-ups',
    ],
    notes: 'Scale: Reduce weight, use ring rows instead of pull-ups',
  },
  {
    name: 'Classic Bodyweight AMRAP',
    type: 'AMRAP',
    duration: 20,
    description: '20 minute AMRAP',
    movements: [
      '5 Pull-ups',
      '10 Push-ups',
      '15 Air Squats',
    ],
    notes: 'Goal: 15+ rounds for experienced athletes',
  },
  {
    name: 'Murph',
    type: 'For Time',
    description: 'Classic hero WOD',
    movements: [
      '1 mile Run',
      '100 Pull-ups',
      '200 Push-ups',
      '300 Air Squats',
      '1 mile Run',
    ],
    notes: 'Optional: Wear 9kg vest. Partition reps as needed (e.g., 20 rounds of 5-10-15)',
  },
  {
    name: 'Annie',
    type: 'For Time',
    description: '50-40-30-20-10 reps for time',
    movements: [
      '50-40-30-20-10 Double-Unders',
      '50-40-30-20-10 Sit-ups',
    ],
    notes: 'Scale double-unders to single-unders (multiply by 3)',
  },

  // AMRAP STYLE WORKOUTS
  {
    name: 'Death by Burpees',
    type: 'EMOM',
    description: 'EMOM until failure',
    movements: [
      'Minute 1: 1 Burpee',
      'Minute 2: 2 Burpees',
      'Minute 3: 3 Burpees',
      '(Continue adding 1 burpee each minute until you cannot complete the required reps)',
    ],
    notes: 'Advanced athletes reach 15+ minutes',
  },
  {
    name: 'CrossFit Total',
    type: 'Custom',
    description: 'Find 1RM of three lifts',
    movements: [
      'Back Squat - 1 Rep Max',
      'Shoulder Press - 1 Rep Max',
      'Deadlift - 1 Rep Max',
    ],
    notes: 'Score is sum of all three lifts. Take multiple attempts to find true max.',
  },

  // METCON WORKOUTS
  {
    name: 'Helen',
    type: 'Rounds',
    description: '3 rounds for time',
    movements: [
      '400m Run',
      '21 Kettlebell Swings (24/16 kg)',
      '12 Pull-ups',
    ],
    notes: 'Target: Sub 12 minutes for advanced athletes',
  },
  {
    name: 'Grace',
    type: 'For Time',
    description: '30 reps for time',
    movements: [
      '30 Clean and Jerks (61/43 kg)',
    ],
    notes: 'Elite time: Sub 3 minutes. Scale weight appropriately.',
  },

  // CUSTOM HIGH-INTENSITY WORKOUTS
  {
    name: 'The Filthy Fifty',
    type: 'Chipper',
    description: 'For time - complete all movements',
    movements: [
      '50 Box Jumps (61/51 cm)',
      '50 Jumping Pull-ups',
      '50 Kettlebell Swings (16/12 kg)',
      '50 Walking Lunges',
      '50 Knees to Elbows',
      '50 Push Press (20/16 kg)',
      '50 Back Extensions',
      '50 Wall Balls (9/6 kg)',
      '50 Burpees',
      '50 Double-Unders',
    ],
    notes: 'Target: 25-35 minutes. This is a long, grinding workout.',
  },
  {
    name: 'DT',
    type: 'Rounds',
    description: '5 rounds for time',
    movements: [
      '12 Deadlifts (70/48 kg)',
      '9 Hang Power Cleans (70/48 kg)',
      '6 Push Jerks (70/48 kg)',
    ],
    notes: 'RX athletes use same barbell for all movements. Target: sub 10 minutes.',
  },

  // EMOM WORKOUTS
  {
    name: 'Tabata Something Else',
    type: 'Tabata',
    duration: 32,
    description: '8 rounds of 20 seconds work, 10 seconds rest',
    movements: [
      'Pull-ups (20 sec on, 10 sec rest) x8',
      'Push-ups (20 sec on, 10 sec rest) x8',
      'Sit-ups (20 sec on, 10 sec rest) x8',
      'Squats (20 sec on, 10 sec rest) x8',
    ],
    notes: 'Score is total reps across all movements. Rest 1 min between movements.',
  },

  // ========================================
  // CUSTOM WORKOUTS
  // ========================================
  
  {
    name: 'Fun Intervals',
    type: 'Rounds',
    duration: 45,
    description: 'Every 15 minutes for 45 minutes (3 rounds)',
    movements: [
      '1000m Bike Erg',
      '20 Russian KB Swings (32/24 kg)',
      '400m Run',
      '20 V-ups',
    ],
    notes: 'Goal: Complete each round in sub 10 minutes, rest remaining time before next round',
  },
  {
    name: 'Odd Object Grind',
    type: 'AMRAP',
    duration: 8,
    description: '8 minute AMRAP x2 rounds (4 min rest between)',
    movements: [
      '5 Bar Muscle-Ups',
      '10 Toes to Bar',
      '5 Heavy Sandbag Cleans (70/50 kg)',
      '50 Double-Unders',
    ],
    notes: 'Complete first 8 min AMRAP, rest 4 minutes, then repeat. Start second AMRAP from bar muscle-ups. Score is total rounds across both AMRAPs.',
  },
  {
    name: 'Gymnastics Capacity Work',
    type: 'For Time',
    description: '3 parts with progressive gymnastics difficulty',
    movements: [
      'Part 1: 21-15-9 Pull-ups + Double DB Squats (22.5/15 kg)',
      'Rest 3 minutes',
      'Part 2: 15-12-9 Chest-to-Bar Pull-ups + Double DB Shoulder-to-Overhead (22.5/15 kg)',
      'Rest 3 minutes',
      'Part 3: 12-9-6 Bar Muscle-Ups + Double DB Thrusters (22.5/15 kg)',
    ],
    notes: 'Progressive gymnastics difficulty: Pull-ups → C2B → BMU. Complete all reps of pull-ups then DB movement for each round. Score is total working time (excluding rest).',
  },
  {
    name: 'Clean Up',
    type: 'For Time',
    description: 'Progressive clean variations for time',
    movements: [
      '3 Rounds: 25 Double-Unders + 5 Power Cleans (70/50 kg)',
      '2 Rounds: 25 Double-Unders + 5 Squat Cleans (70/50 kg)',
      '1 Round: 25 Double-Unders + 5 Clean and Jerks (70/50 kg)',
    ],
    notes: 'Progressive clean difficulty: Power Cleans → Squat Cleans → Clean and Jerks. Total of 6 rounds, 150 double-unders, and 30 cleans. Same weight throughout.',
  },
  {
    name: 'ALST Benchmark',
    type: 'Custom',
    description: 'Multi-part benchmark: 2 for-time rounds + max BMU',
    movements: [
      'Part A1: Buy-in 75 Wall Balls (9/6 kg), then 10 Rounds of 6 Pull-ups + 3 Clean and Jerks (61/43 kg)',
      'Rest 3 minutes',
      'Part A2: Buy-in 75 Wall Balls (9/6 kg), then 10 Rounds of 6 Chest-to-Bar Pull-ups + 3 Snatches (61/43 kg)',
      'Rest 3 minutes',
      'Part B: 3 min AMRAP - Max Bar Muscle-Ups',
    ],
    notes: 'Benchmark test of capacity and skills. Part A tests work capacity under fatigue, Part B tests max skill output. Same wall ball height for M/F. Total: 150 wall balls, 120 pull-ups (60 strict + 60 C2B), 30 C&J, 30 snatches.',
  },
  {
    name: 'Long Weightlifting Session',
    type: 'EMOM',
    duration: 45,
    description: 'Strength and technique under fatigue - Build to heavy singles',
    movements: [
      'Part 1: Every 2 min x 20 min - Clean and Jerks',
      '  Minutes 0-10: 5 reps, start light and gradually increase weight',
      '  Minutes 10-20: Decrease reps (3-2-1), build to heavy single, attempt PR if ready',
      'Rest 5 minutes',
      'Part 2: Every 2 min x 20 min - Snatches',
      '  Minutes 0-10: 5 reps, start light and gradually increase weight',
      '  Minutes 10-20: Decrease reps (3-2-1), build to heavy single, attempt PR if ready',
    ],
    notes: 'Focus on perfect technique early, maintain form as weight increases. This IS the main workout - includes only warm-up and cool-down blocks (no separate skill/strength work needed). Total: 10 sets Clean & Jerk + 10 sets Snatch. Ideal for building strength while preserving technique under fatigue.',
  },
  {
    name: 'SMASH Session Vol 1',
    type: 'Custom',
    duration: 60,
    description: '3-part endurance grinder: Rowing + DT intervals + Gymnastics chipper',
    movements: [
      'Part 1: Rowing Pyramid Intervals',
      '  100m - 200m - 300m - 400m - 500m - 400m - 300m - 200m - 100m',
      '  Rest 1 min between each distance (use C2 rower pre-set intervals with 1 min rest)',
      '  Goal: Maintain consistent pace throughout pyramid',
      'Rest 5+ minutes',
      'Part 2: DT Intervals - 3 Rounds',
      '  4 min AMRAP: DT (12 Deadlifts + 9 Hang Power Cleans + 6 Shoulder-to-Overhead @ 40/30 kg)',
      '  2 min Rest',
      '  Goal: Consistent or increasing rounds each AMRAP, always start from deadlifts',
      'Rest 5+ minutes',
      'Part 3: Gymnastics Chipper - For Time',
      '  10 Bar Muscle-Ups',
      '  20 Chest-to-Bar Pull-ups',
      '  30 Pull-ups',
      '  40 Toes-to-Bar',
      '  Goal: Grind through - grip will be challenged after Part 2',
    ],
    notes: 'PROGRAM ONLY FOR LONG SESSIONS. No skill/strength block needed - this IS the main workout. Rest 5+ min between all 3 parts. Part 3 scaling: Do NOT scale reps, scale movements (BMU→Jumping BMU from box, C2B→Banded C2B, Pull-ups→Banded Pull-ups). Total volume: 2,700m rowing, 3 rounds of DT, 100 pull-up variations.',
  },
  {
    name: 'Bear Going Wild',
    type: 'Custom',
    duration: 60,
    description: '3-part strength and skill complex: Bear Complex + Progressive cleans + BMU ladder',
    movements: [
      'Part 1: Build to Heavy 3 Unbroken Rounds of Bear Complex',
      '  Bear Complex = 1 Power Clean + 1 Front Squat + 1 Push Press + 1 Back Squat + 1 Push Press',
      '  Goal: Find heaviest weight for 3 consecutive unbroken complexes',
      'Rest 5 minutes',
      'Part 2: 90 sec ON / 90 sec OFF - 5 Rounds',
      '  30 Double-Unders',
      '  12 Toes-to-Bar',
      '  Max Cleans in remaining time',
      '  Clean weight progression: 65% → 70% → 75% → 80% → 85% of 1RM (increase 5% each round)',
      'Rest 5 minutes',
      'Part 3: AMRAP 6 minutes - Ascending Ladder',
      '  1 Bar Muscle-Up + 1 Wall Walk',
      '  2 Bar Muscle-Ups + 2 Wall Walks',
      '  3 Bar Muscle-Ups + 3 Wall Walks',
      '  Continue: 4-4, 5-5, 6-6... as far as possible',
    ],
    notes: 'INCLUDES SKILL/STRENGTH - Program only with warm-up and cool-down blocks. Rest 5 min between all parts. Part 1 tests max strength under fatigue. Part 2 challenges metabolic capacity with increasing barbell weight. Part 3 tests gymnastics endurance. Total cleans will vary based on capacity.',
  },
  {
    name: '40 Minutes of Fame',
    type: 'EMOM',
    duration: 50,
    description: '40 min EMOM + descending KB/sit-up finisher',
    movements: [
      'EMOM 40 minutes (10 rounds):',
      '  Minute 1: 15 Cal Echo Bike',
      '  Minute 2: 12 Thrusters (40/30 kg)',
      '  Minute 3: 9 Burpee Pull-ups',
      '  Minute 4: Rest',
      'Clean equipment, then:',
      'For Time: 50-40-30-20-10',
      '  KB Swings (32/24 kg)',
      '  Sit-ups',
    ],
    notes: 'Long session - can include short skill work for thrusters OR burpee pull-ups (choose one). EMOM tests engine across all domains with built-in rest. Finisher is grip and core challenge after 40 min of work. Total: 150 cal bike, 120 thrusters, 90 burpee pull-ups, 150 KB swings, 150 sit-ups.',
  },
  {
    name: 'CF Style Bodybuilding',
    type: 'For Time',
    duration: 60,
    description: 'Progressive bench press + strict gymnastics - grind through with rest',
    movements: [
      'Part 1: 21-15-9',
      '  Bench Press (50/35 kg)',
      '  Strict Pull-ups',
      '  Easy Run 400m',
      'Part 2: 18-12-6',
      '  Bench Press (60/45 kg)',
      '  Strict Chest-to-Bar Pull-ups',
      '  Easy Run 400m',
      'Part 3: 12-6-3',
      '  Bench Press (70/55 kg)',
      '  Strict Bar Muscle-Ups',
    ],
    notes: 'LONG SESSION with lots of rest - main goal is to grind through all reps. Scale gymnastics with bands, scale bench press WEIGHT but NOT reps. Rest as long as needed between reps, aim to complete everything. Total: 66 bench press (progressive weight), 66 strict pull-ups, 800m easy run. This is about volume under tension, not speed.',
  },
  {
    name: 'Midline Challenge',
    type: 'EMOM',
    duration: 42,
    description: 'Every 6 min for 42 min - core and midline focused',
    movements: [
      'Every 6 minutes x 7 rounds:',
      '  750m Row',
      '  5 Wall Walks',
      '  10 Toes-to-Bar',
      '  15 Wall Balls (9/6 kg)',
      'Work completed in 5 min window, 1 min rest',
    ],
    notes: 'NO SKILL/STRENGTH needed - this IS the main workout. Total: 7 rounds. RX scaling: Row 650m, 3 wall walks, 10 knee raises, 15 wall balls (6/4 kg). Total volume: 5,250m row, 35 wall walks, 70 T2B, 105 wall balls. Midline and grip will be tested!',
  },

  // ADD MORE CUSTOM WODS BELOW!
  // Copy the format above and paste your workouts here
  
  // ========================================
  // ADDITIONAL WORKOUTS (99 workouts)
  // ========================================
  
  {
    name: 'Double Under AMRAP',
    type: 'AMRAP',
    duration: 12,
    description: 'Fast cardio and core with jumps and situps',
    movements: [
      '50 Double-unders',
      '30 Sit-ups',
      '20 Air Squats',
    ],
    notes: 'Singles x2 for beginners; target 3–6 rounds',
  },
  {
    name: 'EMOM Power',
    type: 'EMOM',
    duration: 20,
    description: 'Strength + conditioning in 20 minutes',
    movements: [
      'Odd minutes: 5 Power Snatches (34/25 kg)',
      'Even minutes: 12 Calorie Row',
    ],
    notes: 'Reduce snatch weight if form breaks',
  },
  {
    name: 'Chipper of Pain',
    type: 'Chipper',
    duration: 35,
    description: 'Long chipper combining heavy lifts and metcons',
    movements: [
      '50 KB Swings (24/16 kg)',
      '40 Box Jumps (61/51 cm)',
      '30 SDHP (43/29 kg)',
      '20 Burpees',
      '10 Deadlifts (102/70 kg)',
    ],
    notes: 'RX = unbroken where possible; scale KB/box height',
  },
  {
    name: 'Tabata Takedown',
    type: 'Tabata',
    duration: 16,
    description: 'Four Tabata stations, one after another',
    movements: [
      'Tabata (20s on/10s off) x 8 each:',
      'Push-ups',
      'Sit-ups',
      'Squat Jumps',
      'Russian KB Swings (16/11 kg)',
    ],
    notes: 'Count intervals; rest 1 min between stations',
  },
  {
    name: 'Helen Reversed',
    type: 'Rounds',
    duration: 15,
    description: 'Classic triplet flipped',
    movements: [
      '400m Run',
      '21 Kettlebell Swings (32/24 kg)',
      '12 Pull-ups',
    ],
    notes: 'Scale run to row if needed',
  },
  {
    name: 'Ladder Up',
    type: 'For Time',
    duration: 16,
    description: 'Increasing ladder then back down',
    movements: [
      '1-2-3-4-5-4-3-2-1 Thrusters (20/16 kg) & Burpees (same reps)',
    ],
    notes: 'Use lighter thruster weight to keep pace',
  },
  {
    name: '50-40-30-20-10 Grinder',
    type: 'For Time',
    duration: 20,
    description: 'Big rep scheme cardio + strength mix',
    movements: [
      '50-40-30-20-10 Double-unders',
      '50-40-30-20-10 Wall Balls (9/6 kg)',
      '50-40-30-20-10 Calories Bike',
    ],
    notes: 'Swap double-unders for singles where needed',
  },
  {
    name: 'Muscle-Up Builder',
    type: 'EMOM',
    duration: 20,
    description: 'Practice muscle-ups and maintain conditioning',
    movements: [
      'Odd minutes: 3 Chest-to-bar (or progressions)',
      'Even minutes: 10 Box Step-ups + 6 Burpees',
    ],
    notes: 'Substitute banded muscle-up progressions',
  },
  {
    name: 'Dirty Thirty',
    type: 'For Time',
    duration: 25,
    description: '10 movements x 3 rounds (short but nasty)',
    movements: [
      '30 Box Jumps',
      '30 Sit-ups',
      '30 KB Swings (16/11 kg)',
      '30 Walking Lunges (each leg = 1)',
      '30 Push Press (20/14 kg)',
      '30 Pull-ups',
      '30 Wall Balls',
      '30 Russian Twists',
      '30 Calorie Row',
      '30 Burpees',
    ],
    notes: 'Reduce reps to 15 for first timer',
  },
  {
    name: '20-Minute AMRAP — Grinder',
    type: 'AMRAP',
    duration: 20,
    description: 'Steady pace total-body AMRAP',
    movements: [
      '12 Deadlifts (61/43 kg)',
      '9 Hand-release Push-ups',
      '6 Box Jumps (61/51 cm)',
    ],
    notes: 'Keep deadlift weight submax for conditioning',
  },
  {
    name: 'EMOM-10 Sprint',
    type: 'EMOM',
    duration: 10,
    description: 'Short EMOM for power',
    movements: [
      'Minute 1: 3 Power Cleans (61/43 kg)',
      'Minute 2: 6 Burpees over bar',
    ],
    notes: 'Adjust cleans to hang cleans for beginners',
  },
  {
    name: 'Barbell Chipper',
    type: 'Chipper',
    duration: 38,
    description: 'Big barbell tonnage, for time',
    movements: [
      '10 Clean & Jerks (61/43 kg)',
      '20 Front Squats (61/43 kg)',
      '30 Deadlifts (61/43 kg)',
      '40 Thrusters (43/29 kg)',
    ],
    notes: 'Use moderate weight, break sets',
  },
  {
    name: '12 Rounds',
    type: 'Rounds',
    duration: 14,
    description: 'Short repeated couplets',
    movements: [
      '10 Push Press (29/20 kg)',
      '10 Sit-ups',
    ],
    notes: 'Move quickly but controlled; scale weight',
  },
  {
    name: 'Chipper Sprint',
    type: 'For Time',
    duration: 16,
    description: 'Short chipper, sprint finish',
    movements: [
      '1000m Row',
      '50 Air Squats',
      '30 Pull-ups',
      '20 Burpees',
    ],
    notes: 'Split pull-ups; row target pace',
  },
  {
    name: 'Partner Murph Lite',
    type: 'Custom',
    duration: 40,
    description: 'Partner teams split work, heavy cardio + bodyweight',
    movements: [
      'Each person: 800m Run x2',
      'Shared: 100 Pull-ups / 200 Push-ups / 300 Air Squats (or partition)',
    ],
    notes: 'Partition as desired; scale reps',
  },
  {
    name: '20-10 Tabata Mix',
    type: 'Tabata',
    duration: 11,
    description: 'Two Tabata blocks for legs and upper body',
    movements: [
      'Tabata x 8: Air Squats',
      'Tabata x 8: Push-ups',
    ],
    notes: 'Pick controlled range of motion',
  },
  {
    name: 'Run & Rip',
    type: 'For Time',
    duration: 25,
    description: 'Running + kettlebell lunges',
    movements: [
      '800m Run',
      '24 KB Lunges (12/arm) (11/7 kg)',
      '15 Burpees',
    ],
    notes: 'Use lighter KB if needed',
  },
  {
    name: '10-Min AMRAP — Strength Finish',
    type: 'AMRAP',
    duration: 10,
    description: 'Short, intense, moderate weight',
    movements: [
      '5 Heavy Deadlifts (84/61 kg)',
      '10 Toes-to-Bar',
      '15 Box Jumps (61/51 cm)',
    ],
    notes: 'Use lighter deadlift if TTB volume too high',
  },
  {
    name: 'EMOM Complex',
    type: 'EMOM',
    duration: 16,
    description: 'Strength complex repeated within minutes',
    movements: [
      'Minute 1: 6 Front Squats (43/29 kg)',
      'Minute 2: 8 Pull-ups (or ring rows)',
    ],
    notes: 'Use manageable weight so second minute stays crisp',
  },
  {
    name: '21-15-9 Fight',
    type: 'For Time',
    duration: 15,
    description: 'Classic CrossFit rep scheme with mix',
    movements: [
      '21-15-9 Thrusters (43/29 kg)',
      '21-15-9 Pull-ups',
      '21-15-9 Calories Assault Bike',
    ],
    notes: 'Reduce thruster weight for sub-10 target',
  },
  {
    name: 'Gymnastics EMOM',
    type: 'EMOM',
    duration: 20,
    description: 'Skill practice and conditioning for gymnasts',
    movements: [
      'Odd minutes: 6 Kipping Pull-ups or progressions',
      'Even minutes: 8/each Pistols (or assisted)',
    ],
    notes: 'Substitute single-leg box step-downs for pistols',
  },
  {
    name: 'Bodyweight Power AMRAP',
    type: 'AMRAP',
    duration: 20,
    description: 'Classic bodyweight AMRAP with strict push-ups',
    movements: [
      '5 Pull-ups',
      '10 Push-ups (strict)',
      '15 Air Squats',
    ],
    notes: 'Scale pull-ups to ring rows',
  },
  {
    name: 'Row & Ram',
    type: 'Rounds',
    duration: 23,
    description: 'Mixed cardio-strength intervals',
    movements: [
      '500m Row',
      '12 Hang Power Cleans (43/29 kg)',
      '15 Sit-ups',
    ],
    notes: 'Reduce cleans for pace',
  },
  {
    name: 'Heavy 7s',
    type: 'For Time',
    duration: 20,
    description: '7 reps across big lifts — heavy but short',
    movements: [
      '7 Back Squats (93/66 kg)',
      '7 Burpees',
    ],
    notes: 'Sub moderate weight if 7×7 is too heavy',
  },
  {
    name: 'Farmer\'s Fury',
    type: 'For Time',
    duration: 28,
    description: 'Grip and conditioning with carries and sprints',
    movements: [
      '800m Farmer Carry (2×32/23 kg)',
      '400m Run',
      '2×200m Sled Push (heavy)',
    ],
    notes: 'Break carries as needed',
  },
  {
    name: 'Tabata Metcon Ladder',
    type: 'Tabata',
    duration: 20,
    description: 'Tabata ladder increasing intensity',
    movements: [
      'Tabata 1: Burpees',
      'Tabata 2: KB Swings',
      'Tabata 3: Pull-ups',
      'Tabata 4: Air Squats',
    ],
    notes: 'Keep technique strict',
  },
  {
    name: 'The Chipper 400',
    type: 'Chipper',
    duration: 40,
    description: '400 reps split among stations',
    movements: [
      '100 Air Squats',
      '80 Sit-ups',
      '70 Double-unders (or 140 singles)',
      '60 Lunges (each count)',
      '50 Push-ups',
      '40 Pull-ups',
    ],
    notes: 'Partition to maintain pace',
  },
  {
    name: '20-Minute EMOM Strength + Cardio',
    type: 'EMOM',
    duration: 20,
    description: 'Alternate heavy sets and sprint rows',
    movements: [
      'Odd minutes: 4 Back Squats (70/48 kg)',
      'Even minutes: 15 Cal Bike calories',
    ],
    notes: 'Reduce squat weight if form fades',
  },
  {
    name: '400m Repeat Special',
    type: 'Rounds',
    duration: 25,
    description: 'Classic running interval WOD',
    movements: [
      '400m Run',
      '15 Wall Balls (9/6 kg)',
    ],
    notes: 'Run pace steady, scale wall ball reps',
  },
  {
    name: '30-20-10 Barbell',
    type: 'For Time',
    duration: 13,
    description: 'Descending rep scheme with barbell and burpees',
    movements: [
      '30-20-10 Deadlifts (61/43 kg)',
      '30-20-10 Burpees over bar',
    ],
    notes: 'Choose deadlift weight that allows movement',
  },
  {
    name: 'Mixed Modal AMRAP',
    type: 'AMRAP',
    duration: 18,
    description: 'Balanced mixed modal AMRAP',
    movements: [
      '12 Wall Balls',
      '9 Pull-ups',
      '6 Power Cleans (52/34 kg)',
    ],
    notes: 'Break to avoid failure',
  },
  {
    name: 'Tabata Upper Burn',
    type: 'Tabata',
    duration: 16,
    description: 'Upper-body focused Tabata block',
    movements: [
      'Tabata x 8: Push-ups',
      'Tabata x 8: Rows (barbell or TRX)',
    ],
    notes: 'Keep strict reps',
  },
  {
    name: 'The 1-RM Complex',
    type: 'Custom',
    duration: 38,
    description: 'Work up to heavy single for a complex',
    movements: [
      'EMOM 12 (build): 1 Complex: Clean + Front Squat + Jerk — work to heavy single',
    ],
    notes: 'Warm thoroughly; coach spots recommended',
  },
  {
    name: 'Bike & Burpee Hell',
    type: 'Rounds',
    duration: 23,
    description: 'Calorie bike and burpee intervals',
    movements: [
      '12 cal Bike',
      '8 Burpees',
    ],
    notes: 'Scale calories according to bike model',
  },
  {
    name: 'Bar Muscle-Up Triplet',
    type: 'AMRAP',
    duration: 15,
    description: 'Gymnastics heavy AMRAP',
    movements: [
      '3 Bar MU (or 6 Ring Rows)',
      '6 Handstand Push-ups (or pike)',
      '9 Toes-to-bar',
    ],
    notes: 'Scale muscle-ups to jumping transitions',
  },
  {
    name: 'Odd Ladder',
    type: 'For Time',
    duration: 15,
    description: 'Only odd numbered reps',
    movements: [
      '1-3-5-7-9-11-13 Thrusters (20/16 kg)',
      '1-3-5-7-9-11-13 Burpees (same reps)',
    ],
    notes: 'Build rhythm, keep breathing',
  },
  {
    name: '30-Minute AMRAP — Heavy Singles',
    type: 'AMRAP',
    duration: 30,
    description: 'Long AMRAP alternating heavy single lifts and bodyweight',
    movements: [
      '1 Heavy Clean (work up to 60% 1RM)',
      '10 Push-ups',
      '15 Air Squats',
      '200m Run',
    ],
    notes: 'Keep heavy singles submax to avoid failure',
  },
  {
    name: 'Shuffle & Push',
    type: 'EMOM',
    duration: 12,
    description: 'Short EMOM with shuttle runs and push presses',
    movements: [
      'Odd minutes: Shuttle 3×25m',
      'Even minutes: 10 Push Press (34/25 kg)',
    ],
    notes: 'Good for team/partner alternation',
  },
  {
    name: 'The 5-5-5 Grinder',
    type: 'Rounds',
    duration: 25,
    description: '5 rounds of 5s at moderate weight',
    movements: [
      '5 Deadlifts (102/70 kg)',
      '5 Ring Dips',
      '400m Run',
    ],
    notes: 'Scale DL weight for conditioning',
  },
  {
    name: 'Lactic Acid Ladder',
    type: 'For Time',
    duration: 20,
    description: '1-2-3-4-5 ladder of thrusters and jump rope',
    movements: [
      'Ladder up and down: Thrusters (29/20 kg)',
      '30/20/10 Double-unders per ladder step',
    ],
    notes: 'Singles allowed',
  },
  {
    name: 'Strongman Chipper',
    type: 'Chipper',
    duration: 40,
    description: 'Tires, yoke, carries and sleds',
    movements: [
      '50m Tire Flip',
      '100m Yoke Carry (moderate)',
      '2×50m Farmer Carry',
      '3×20m Sled Push (heavy)',
    ],
    notes: 'Use safety equipment for flips',
  },
  {
    name: 'EMOM Ladder',
    type: 'EMOM',
    duration: 20,
    description: 'Build sets every minute',
    movements: [
      'Minute 1: 1 Power Clean',
      'Minute 2: 2 Power Cleans',
      'Minute 3: 3 Power Cleans',
      'Minute 4: 4 Power Cleans',
      'Minute 5: 5 Power Cleans',
      'Then back down: 4-3-2-1',
      'Rest: 10 Sit-ups on rest time',
    ],
    notes: 'Manage load to avoid form loss',
  },
  {
    name: '50-Rep Grab',
    type: 'For Time',
    duration: 28,
    description: '50 total reps across three big movements',
    movements: [
      '50 Thrusters (20/16 kg)',
      '50 Pull-ups',
      '50 Box Jumps',
    ],
    notes: 'Partition as needed',
  },
  {
    name: 'Heavy Pull EMOM',
    type: 'EMOM',
    duration: 15,
    description: 'Strengthened pulling under fatigue',
    movements: [
      'Odd minutes: 3 Heavy Deadlifts (84/61 kg)',
      'Even minutes: 10 Box Jumps',
    ],
    notes: 'Keep DL heavy but submax',
  },
  {
    name: 'Core Tabata Circuit',
    type: 'Tabata',
    duration: 20,
    description: 'Four core Tabata moves',
    movements: [
      'Tabata x 8: Plank Hold (20s active modify)',
      'Tabata x 8: V-ups',
      'Tabata x 8: Hollow Rocks',
      'Tabata x 8: Mountain Climbers',
    ],
    notes: 'Maintain neutral spine',
  },
  {
    name: 'Annie Variation',
    type: 'For Time',
    duration: 13,
    description: 'Classic with a twist',
    movements: [
      '50-40-30-20-10 Double-unders',
      '50-40-30-20-10 Sit-ups',
    ],
    notes: 'Singles = 100-80-60 etc',
  },
  {
    name: 'Kettlebell Chipper',
    type: 'Chipper',
    duration: 40,
    description: 'All kettlebell, mixed rep ranges',
    movements: [
      '100 Single-arm KB Swings (23/16 kg)',
      '80 KB Goblet Squats',
      '60 KB High Pulls',
      '40 KB Lunges',
      '20 KB Turkish Get-ups (10/side)',
    ],
    notes: 'Alternate sides, use moderate weight',
  },
  {
    name: '30-Minute AMRAP — Legs Only',
    type: 'AMRAP',
    duration: 30,
    description: 'Brutal lower-body focus',
    movements: [
      '15 Back Squats (43/29 kg)',
      '12 Box Jumps',
      '9 Walking Lunges (each leg count = 1)',
    ],
    notes: 'Reduce squat weight to maintain rounds',
  },
  {
    name: 'EMOM Sprint Intervals',
    type: 'EMOM',
    duration: 12,
    description: 'Short max effort intervals for power',
    movements: [
      'Odd minutes: 12 Cal Bike sprint',
      'Even minutes: 10 Burpees',
    ],
    notes: 'Go hard on sprints, recover on burpees',
  },
  {
    name: 'Grace Lite',
    type: 'For Time',
    duration: 12,
    description: 'Barbell clean and jerks but lower rep/weight',
    movements: [
      '30 Clean & Jerks (43/29 kg)',
    ],
    notes: 'Partition across sets to maintain speed',
  },
  {
    name: '21-Minute Chipper',
    type: 'Chipper',
    duration: 26,
    description: '21-minute AMRAP? — actually a chipper for time',
    movements: [
      '21 Cal Row',
      '21 Thrusters (20/16 kg)',
      '21 Pull-ups',
      '21 Box Jumps',
      '21 Sit-ups',
    ],
    notes: 'Break smartly',
  },
  {
    name: 'Handstand EMOM Skill',
    type: 'EMOM',
    duration: 18,
    description: 'Build handstand strength + short metcon',
    movements: [
      'Odd minutes: 60s Handstand practice/holds',
      'Even minutes: 12/each DB Snatch (16/11 kg)',
    ],
    notes: 'Sub pike push-ups for handstand progressions',
  },
  {
    name: 'Death by Burpee',
    type: 'AMRAP',
    duration: 15,
    description: 'Classic "Death by" increasing reps each minute',
    movements: [
      'Minute 1: 1 Burpee',
      'Minute 2: 2 Burpees',
      'Minute 3: 3 Burpees',
      '(Continue adding 1 burpee each minute until failure)',
    ],
    notes: 'Stop when you can\'t complete required reps in minute',
  },
  {
    name: 'The Grinder 60',
    type: 'AMRAP',
    duration: 60,
    description: '60-minute long endurance AMRAP (scale to 40+)',
    movements: [
      '400m Run',
      '20 Push-ups',
      '15 Squats',
      '10 Pull-ups',
    ],
    notes: 'Scale to 40 min for most athletes',
  },
  {
    name: 'Power Clean Ladder',
    type: 'Rounds',
    duration: 20,
    description: 'Build power cleans then sprint',
    movements: [
      'Every 2 minutes for 20 min: work to a heavy single power clean + 10 burpees in leftover time',
    ],
    notes: 'Safety first on heavy lifts',
  },
  {
    name: 'Barbell & Bike',
    type: 'For Time',
    duration: 25,
    description: 'Alternate cal bike efforts with heavy barbell sets',
    movements: [
      '15 Cal bike',
      '12 Deadlifts (70/48 kg)',
    ],
    notes: 'Moderate DL chosen for volume',
  },
  {
    name: 'Tabata Lower Burn',
    type: 'Tabata',
    duration: 18,
    description: 'Four lower-body Tabata intervals',
    movements: [
      'Tabata x4: Squat Jumps',
      'Tabata x4: Alternating Lunges',
      'Tabata x4: KB Swing',
      'Tabata x4: Wall Sits (active holds instead of rest)',
    ],
    notes: 'Keep depth safe on lunges',
  },
  {
    name: '50/40/30/20/10 Sprint Chipper',
    type: 'For Time',
    duration: 33,
    description: 'Descending rep chipper with mixed movements',
    movements: [
      '50-40-30-20-10 Calories Row',
      '50-40-30-20-10 Kettlebell Swings',
      '50-40-30-20-10 Box Jumps',
      '50-40-30-20-10 Push-ups',
      '50-40-30-20-10 Sit-ups',
    ],
    notes: 'Partition to pace',
  },
  {
    name: 'Gymnastics Ladder',
    type: 'For Time',
    duration: 25,
    description: 'Progressing gymnastic movement ladder',
    movements: [
      '1-2-3-4-5 ladder: Ring Muscle-up attempts (or progressions), HSPU attempts, Pistols (per leg)',
    ],
    notes: 'Use progressions when skills not mastered',
  },
  {
    name: 'The Bear Complex',
    type: 'Rounds',
    duration: 20,
    description: 'Classic barbell complex repeated for rounds',
    movements: [
      '7 Bear Complex (Power Clean, Front Squat, Push Press, Back Squat, Push Press — count as 1 rep) (43/29 kg)',
    ],
    notes: 'Use lighter weight for full complexes',
  },
  {
    name: 'EMOM & Chipper Hybrid',
    type: 'Custom',
    duration: 30,
    description: 'Start EMOM then finish with for-time chipper',
    movements: [
      'EMOM 12: 10 Cal Row',
      'Then For Time: 21-15-9 Thrusters & Pull-ups',
    ],
    notes: 'Adjust EMOM cal target',
  },
  {
    name: 'Endurance Run Mix',
    type: 'Rounds',
    duration: 50,
    description: 'Running and bodyweight intervals',
    movements: [
      '1600m Run',
      '50 Air Squats',
      '30 Push-ups',
    ],
    notes: 'Pace run conservatively',
  },
  {
    name: 'The Triple Tabata',
    type: 'Tabata',
    duration: 23,
    description: 'Three different Tabata blocks with active rest',
    movements: [
      'Tabata 1: Row calories',
      'Tabata 2: Push-ups',
      'Tabata 3: Squat jumps',
    ],
    notes: 'Monitor row cal equivalence',
  },
  {
    name: 'Power Snatch EMOM',
    type: 'EMOM',
    duration: 20,
    description: 'Build power snatch under fatigue',
    movements: [
      'Odd minutes: 3 Power Snatches (34/25 kg)',
      'Even minutes: 10 Box Jumps',
    ],
    notes: 'Lower weight if technical errors appear',
  },
  {
    name: 'Chipper of the Deadlift',
    type: 'Chipper',
    duration: 50,
    description: 'Huge deadlift volume mixed with metcon',
    movements: [
      '100 Deadlifts (43/29 kg)',
      '80 Sit-ups',
      '60 Box Jumps',
      '40 Push-ups',
      '20 Handstand Holds (sec total)',
    ],
    notes: 'Use lower DL weight to survive volume',
  },
  {
    name: 'Ladder AMRAP',
    type: 'AMRAP',
    duration: 20,
    description: 'Climbs ladder each round within time cap',
    movements: [
      'Round 1: 1 Thruster + 1 Pull-up',
      'Round 2: 2 & 2',
      'Round 3: 3 & 3',
      '(Continue climbing ladder)',
    ],
    notes: 'Rx weight light enough to climb',
  },
  {
    name: 'Classic Couplets',
    type: 'Rounds',
    duration: 25,
    description: '10 rounds of two movements — steady',
    movements: [
      '10 Calories Row',
      '10 Push Press (29/20 kg)',
    ],
    notes: 'Maintain steady pace',
  },
  {
    name: 'Pyramid Chipper',
    type: 'For Time',
    duration: 20,
    description: 'Pyramid rep scheme high to low',
    movements: [
      '10-8-6-4-2 (and back) Thrusters (43/29 kg)',
      '10-8-6-4-2 (and back) Burpees',
    ],
    notes: 'Scale thruster weight',
  },
  {
    name: 'Sled & Sprint EMOM',
    type: 'EMOM',
    duration: 15,
    description: 'Short heavy sled pushes with sprint recovery',
    movements: [
      'Odd minutes: 3×15m Sled Push (heavy)',
      'Even minutes: 30s easy jog or rest',
    ],
    notes: 'Use alternating athletes where possible',
  },
  {
    name: '30-20-10 Gymnastics',
    type: 'For Time',
    duration: 20,
    description: 'High-rep gymnastics-heavy chipper',
    movements: [
      '30-20-10 Toes-to-bar',
      '30-20-10 Ring Dips',
      '30-20-10 Handstand Push-ups (scale)',
    ],
    notes: 'Substitute knee raises/push-ups as needed',
  },
  {
    name: 'The 5K Row',
    type: 'For Time',
    duration: 22,
    description: 'Middle-distance aerobic test',
    movements: [
      '5,000m Row for time',
    ],
    notes: 'Pacing strategy required',
  },
  {
    name: 'Push/Pull Ladder',
    type: 'Rounds',
    duration: 25,
    description: 'Increasing push and pull volume',
    movements: [
      'Round 1: 5 Push-press / 5 Bent-over Row (moderate weight)',
      'Round 2: 10 & 10',
      'Round 3: 15 & 15',
      'Round 4: 20 & 20',
      'Round 5: 25 & 25',
    ],
    notes: 'Choose weight for consistent sets',
  },
  {
    name: 'Deck of Cards',
    type: 'Custom',
    duration: 30,
    description: 'Use a deck to randomly generate reps/movements',
    movements: [
      'Assign each suit to a movement:',
      'Hearts = Burpees',
      'Spades = Air Squats',
      'Diamonds = Sit-ups',
      'Clubs = Pull-ups',
      'Face cards = 10, A = 1. Draw until deck done',
    ],
    notes: 'Great scalable game WOD',
  },
  {
    name: 'Midline Mixer',
    type: 'Custom',
    duration: 25,
    description: 'Tabata core followed by AMRAP total body',
    movements: [
      'Tabata core (plank/V-ups)',
      'Then 12 min AMRAP: 12 KB Swing, 9 Push-ups, 6 Pull-ups',
    ],
    notes: 'Focus on core engagement',
  },
  {
    name: 'Snatch EMOM Progression',
    type: 'EMOM',
    duration: 20,
    description: 'Technical snatch practice building to heavy single',
    movements: [
      'Every minute: 2 Snatch pulls + 1 Power Snatch (build)',
    ],
    notes: 'Emphasize technique, not load',
  },
  {
    name: '300-Rep Grinder',
    type: 'Chipper',
    duration: 40,
    description: '300 total reps across simple movements',
    movements: [
      '100 Air Squats',
      '80 Sit-ups',
      '60 Push-ups',
      '40 Lunges',
      '20 Pull-ups',
    ],
    notes: 'Pace for consistent sets',
  },
  {
    name: '10-Minute AMRAP — Sprint',
    type: 'AMRAP',
    duration: 10,
    description: 'Short, high-tempo with sprint piece',
    movements: [
      '10/8/6 calories bike',
      '10 Burpees',
      '10 Sit-ups',
      '(Repeat)',
    ],
    notes: 'Expect high heart rate',
  },
  {
    name: 'Clean Ladder For Time',
    type: 'For Time',
    duration: 28,
    description: 'Add 1 clean each round, fast transitions',
    movements: [
      '1+2+3...+10 Cleans at 65–75% of 1RM + 10 burpees every 5 rounds',
    ],
    notes: 'Scale weight to manage volume',
  },
  {
    name: 'Gymnastic Couplets',
    type: 'Rounds',
    duration: 28,
    description: 'Frequent gymnastics practice within metcon',
    movements: [
      '3 Muscle-up attempts (or 6 pull-up progressions)',
      '10 Pistols (or 20 step-downs)',
    ],
    notes: 'Prioritize technique',
  },
  {
    name: '400m Run Chipper',
    type: 'For Time',
    duration: 28,
    description: 'Repeated runs with strength at intervals',
    movements: [
      '400m Run',
      '25 Air Squats',
      '15 Push-press (34/25 kg)',
    ],
    notes: 'Choose push-press weight for sustainable pace',
  },
  {
    name: 'The 8-Minute EMOM Blast',
    type: 'EMOM',
    duration: 8,
    description: 'Short blast for power and coordination',
    movements: [
      'Odd minutes: 8 Power Snatches (light)',
      'Even minutes: 12 Calories Row',
    ],
    notes: 'Good for warmups',
  },
  {
    name: 'Heavy Front Squat AMRAP',
    type: 'AMRAP',
    duration: 12,
    description: 'Build low-rep heavy front squats under time',
    movements: [
      '5 Front Squats (61/43 kg)',
      '10 Sit-ups',
    ],
    notes: 'Use manageable weight that allows 3–5 reps per set',
  },
  {
    name: 'Classic Chipper 800',
    type: 'Chipper',
    duration: 58,
    description: '800m run + 800 reps (split) — intense long chipper',
    movements: [
      '800m Run',
      '200 Air Squats',
      '200 Sit-ups',
      '200 Push-ups (knee allowed)',
      '200 Singles (double-under subs)',
    ],
    notes: 'Partition heavily for time and safety',
  },
  {
    name: 'Pyramid EMOM',
    type: 'EMOM',
    duration: 18,
    description: 'Pyramid rep scheme inside EMOM',
    movements: [
      'Minute 1: 5 Thrusters',
      'Minute 2: 7 Pull-ups',
      'Minute 3: 9 Box Jumps',
      '(Repeat 2×)',
    ],
    notes: 'Adjust reps down if RX weight slows you',
  },
  {
    name: 'The Sprint Chipper',
    type: 'For Time',
    duration: 9,
    description: 'Very short, sharp WOD meant to be all-out',
    movements: [
      '21-15-9 Calories Assault Bike',
      '21-15-9 Burpees',
    ],
    notes: 'Give maximal effort',
  },
  {
    name: '20-Minute Descend',
    type: 'AMRAP',
    duration: 20,
    description: 'Descending reps every round AMRAP style',
    movements: [
      'Round 1: 50 Air Squats, 200m Run',
      'Round 2: 40 Air Squats, 200m Run',
      'Round 3: 30 Air Squats, 200m Run',
      'Round 4: 20 Air Squats, 200m Run',
      'Round 5: 10 Air Squats, 200m Run',
    ],
    notes: 'Break into manageable sets',
  },
  {
    name: 'Tabata Clean & Jerk',
    type: 'Tabata',
    duration: 5,
    description: 'Tabata barbell quick work (light)',
    movements: [
      'Tabata: Barbell Clean & Jerk (empty bar or light) 20s on/10s off x8 — focus on speed',
    ],
    notes: 'Use very light load and perfect mechanics',
  },
  {
    name: 'The 1000m Pyramid',
    type: 'For Time',
    duration: 40,
    description: 'Repeated 1000m rows with decreasing rest',
    movements: [
      '1000m Row',
      '50 Push-ups',
      '25 Pull-ups',
    ],
    notes: 'Pace rows',
  },
  {
    name: 'Metcon Machine',
    type: 'Rounds',
    duration: 30,
    description: 'Heavy engine builder of mixed modal intervals',
    movements: [
      '500m Row',
      '15 KB Swings (32/24 kg)',
      '12 Thrusters (43/29 kg)',
    ],
    notes: 'Keep thruster weight moderate',
  },
  {
    name: 'The 6-Station Chipper',
    type: 'Chipper',
    duration: 53,
    description: '6 stations each 100 reps total',
    movements: [
      '100 reps: Single-arm DB Snatches (alternating count = 100 total)',
      '100 Sit-ups',
      '100 Air Squats',
      '100 Pull-ups (or ring rows)',
      '100 Box Step-ups',
      '100 Jump Rope (100 DU/200 singles)',
    ],
    notes: 'Partition to avoid burning out early',
  },
  {
    name: 'Speed Clean EMOM',
    type: 'EMOM',
    duration: 12,
    description: 'Fast breathing cleans for technique',
    movements: [
      'Minute 1: 4 Speed Cleans (light)',
      'Minute 2: 10 Push-ups',
    ],
    notes: 'Prioritize speed and form',
  },
  {
    name: 'Burpee Ladder',
    type: 'For Time',
    duration: 20,
    description: 'Increasing burpee ladder with set of squats',
    movements: [
      '1-2-3-…-10 Burpees',
      '10 Air Squats after each ladder step',
    ],
    notes: 'Pace to avoid early failure',
  },
  {
    name: 'Slippery 15',
    type: 'AMRAP',
    duration: 15,
    description: '15-minute AMRAP mixing light weights and gymnastics',
    movements: [
      '10 DB Thrusters (11/9 kg)',
      '10 Pull-ups',
      '10 Burpees',
    ],
    notes: 'Keep unbroken where possible',
  },
  {
    name: 'The Chipper 20',
    type: 'Chipper',
    duration: 40,
    description: '20 reps each of 10 movements',
    movements: [
      '20 Deadlifts (43 kg)',
      '20 Box Jumps',
      '20 Pull-ups',
      '20 Push-press',
      '20 Sit-ups',
      '20 KB Swings',
      '20 Wall Balls',
      '20 Lunges (each leg = count 1)',
      '20 Cal Row',
      '20 Hand-release Push-ups',
    ],
    notes: 'Rx to scale',
  },
  {
    name: 'Ascend EMOM',
    type: 'EMOM',
    duration: 24,
    description: 'Increase reps every 2 minutes',
    movements: [
      'Minute 1: 3 Power Snatches',
      'Minute 2: 6 Push-ups',
      'Minute 3: 9 Air Squats',
      '(Repeat with +1 each cycle)',
    ],
    notes: 'Stop when form breaks; reduce accumulation',
  },
  {
    name: 'Heavy Split',
    type: 'Custom',
    duration: 50,
    description: 'Heavy singles plus conditioning',
    movements: [
      'Work to heavy 1RM Back Squat',
      'Then For Time: 5 rounds: 200m Run, 10 Burpees',
    ],
    notes: 'Warm up well for 1RM; rest as needed',
  },
  {
    name: 'Couplet Chaos',
    type: 'Rounds',
    duration: 25,
    description: 'Short couplet repeated for time',
    movements: [
      '21 Wall Balls',
      '12 Deadlifts (61/43 kg)',
    ],
    notes: 'Break wall balls every 7–10',
  },
  {
    name: 'Endurance AMRAP',
    type: 'AMRAP',
    duration: 40,
    description: '40+ minute endurance AMRAP (long)',
    movements: [
      '400m Run',
      '25 Air Squats',
      '10 Pull-ups',
      '5 Burpees',
    ],
    notes: 'Pace for longevity; partition pull-ups',
  },
  {
    name: 'The Everything WOD',
    type: 'Custom',
    duration: 45,
    description: 'A 45-minute mixed workout: strength + EMOM + chipper finish',
    movements: [
      'Part A: Strength 15 min — work to heavy 3RM Clean & Jerk',
      'Part B: 12-min EMOM — odd: 12 Cal Row, even: 12 Ring Rows',
      'Part C: For Time — 50 Wall Balls, 40 KB Swings, 30 Box Jumps, 20 Burpees, 10 Muscle-up attempts (or 20 Pull-ups)',
    ],
    notes: 'Scalable; choose weights to sustain whole session',
  },

  // ========================================
  // ADDITIONAL WORKOUTS (50 more workouts)
  // ========================================

  {
    name: 'No-Equipment Bomber',
    type: 'For Time',
    duration: 18,
    description: 'Minimal gear, full body',
    movements: [
      '400m Run',
      '50 Air Squats',
      '40 Sit-ups',
      '30 Burpees',
      '20 Push-ups',
      '10 Lunges (each leg)',
    ],
    notes: 'Ideal when no weights available. From a "no-equipment workouts" list',
  },
  {
    name: 'Interval Sprint Bodyweight',
    type: 'Rounds',
    duration: 23,
    description: 'Repeated bodyweight + sprint',
    movements: [
      '10 Push-ups',
      '10 Air Squats',
      '200m Sprint',
    ],
    notes: 'Scale sprint distance if needed. Inspired by home workout list',
  },
  {
    name: 'Strict Bodyweight AMRAP',
    type: 'AMRAP',
    duration: 20,
    description: '20-minute strict bodyweight AMRAP',
    movements: [
      '5 Strict Pull-ups',
      '10 Press-ups',
      '15 Air Squats',
    ],
    notes: 'Good for minimal equipment. From gym-friendly list',
  },
  {
    name: 'Kettlebell DT Variation',
    type: 'For Time',
    duration: 18,
    description: 'Kettlebell version of barbell complex',
    movements: [
      '12 KB Swings (two-handed)',
      '9 KB Cleans (two-handed)',
      '6 KB Push-presses (two-handed)',
    ],
    notes: 'Choose moderate KB. From "regular gym" list',
  },
  {
    name: 'Death by Air Bike',
    type: 'EMOM',
    duration: 13,
    description: 'EMOM increasing calories until failure',
    movements: [
      'Minute 1: 2 cal Air Bike',
      'Minute 2: 4 cal',
      'Minute 3: 6 cal',
      '(Continue adding 2 cal each minute until failure)',
    ],
    notes: 'Classic "death by" style cardio. From non-CF.com list',
  },
  {
    name: 'Run & Core Double Mile',
    type: 'For Time',
    duration: 25,
    description: 'Run, core, run',
    movements: [
      '1 mile Run',
      '100 Sit-ups',
      '100 Supermans',
      '1 mile Run',
    ],
    notes: 'Focus on sustained endurance. From home workout list',
  },
  {
    name: 'Outdoor Bodyweight Chipper',
    type: 'Chipper',
    duration: 35,
    description: 'Fixed rep counts bodyweight outside',
    movements: [
      '50 Pull-ups (or ring rows)',
      '100 Push-ups',
      '150 Air Squats',
      '200 Sit-ups',
    ],
    notes: 'Partition as required. Inspired by outdoor WOD list',
  },
  {
    name: 'Hill Sprint + Tuck-Ups',
    type: 'Rounds',
    duration: 18,
    description: 'Hill sprints with core',
    movements: [
      'Hill sprint (~100m)',
      '25 Tuck-ups',
    ],
    notes: 'Use incline if no hill. From no-equipment list',
  },
  {
    name: '300 Air Squat Test',
    type: 'For Time',
    duration: 15,
    description: '300 air squats for time',
    movements: [
      '300 Air Squats',
    ],
    notes: 'Straightforward test of leg endurance',
  },
  {
    name: 'Gymnastic Mastery AMRAP',
    type: 'AMRAP',
    duration: 20,
    description: 'Gymnastics heavy',
    movements: [
      '5 Handstand Push-ups (or pike)',
      '10 Pistol Squats',
      '15 Toes-to-Bar (or knee raises)',
    ],
    notes: 'Scale pistols/hspu accordingly. From at-home list',
  },
  {
    name: 'Fantastic 50 Full Body',
    type: 'For Time',
    duration: 35,
    description: '50 reps of many movements',
    movements: [
      '50 Jump Tucks',
      '50 Push-ups',
      '50 Air Squats',
      '50 Hand-stands (sec or reps)',
      '50 Walking Lunges',
      '50 Sit-ups',
      '50-sec L-Sit hold',
      '50 Burpees',
    ],
    notes: 'Good all-rounder. From home list',
  },
  {
    name: '5k Run Test',
    type: 'For Time',
    duration: 24,
    description: 'Run 5,000 m as fast as possible',
    movements: [
      'Row or run 5k',
    ],
    notes: 'Good cardio benchmark. From home list',
  },
  {
    name: 'Partner Relay 400m + KB Snatches + Burpees',
    type: 'Custom',
    duration: 35,
    description: 'Two-person alternating relay',
    movements: [
      '400m Run',
      '30 KB Snatches (11/7 kg)',
      '30 Burpees (partners alternate)',
    ],
    notes: 'From partner WOD compilation',
  },
  {
    name: 'Partner Chip 100-200-300-400',
    type: 'Custom',
    duration: 40,
    description: 'One partner works while other rests, then switch',
    movements: [
      '100 Pull-ups',
      '200 Push-ups',
      '300 Air Squats',
      '400 Double-unders (or 800 singles)',
    ],
    notes: 'Partners divide reps; good for two. From partner list',
  },
  {
    name: 'Air Squat AMRAP 15',
    type: 'AMRAP',
    duration: 15,
    description: 'Bodyweight legs only',
    movements: [
      '30 Air Squats',
      '15 Sit-ups',
      '10 Lunges (each leg)',
    ],
    notes: 'Simple but effective',
  },
  {
    name: 'Heavy Barbell & Run Combo',
    type: 'For Time',
    duration: 25,
    description: 'Mixed strength + cardio',
    movements: [
      '400m Run',
      '12 Deadlifts (84/61 kg)',
    ],
    notes: 'Choose a deadlift weight you can manage for reps',
  },
  {
    name: 'EMOM Tabata Hybrid',
    type: 'Custom',
    duration: 20,
    description: 'EMOM for first half, Tabata second half',
    movements: [
      '12-min EMOM: Minute 1: 10 KB Swings, Minute 2: 10 Box Jumps',
      'Then Tabata (20s on/10s off) x8 Burpees',
    ],
    notes: 'Good mixed format',
  },
  {
    name: 'Chipper 50-40-30-20-10 Cardio/Strength',
    type: 'For Time',
    duration: 20,
    description: 'Descending reps mixed cardio and strength',
    movements: [
      '50-40-30-20-10 Calories Row',
      '50-40-30-20-10 Wall-Balls (9/6 kg)',
      '50-40-30-20-10 Push-ups',
    ],
    notes: 'Partition as needed',
  },
  {
    name: '30-20-10 Burpee / Lunges / Russian Twists',
    type: 'For Time',
    duration: 13,
    description: 'Big rep chipper',
    movements: [
      '30 Burpees',
      '20 Jumping Lunges (each leg)',
      '10 Russian Twists (11/7 kg)',
    ],
    notes: 'Good quick finisher. From outdoor WOD list',
  },
  {
    name: 'Walking Lunge Marathon',
    type: 'For Time',
    duration: 25,
    description: 'Endurance lower-body carry',
    movements: [
      '200m Walking Lunge (each rep = one step)',
      '10 min max calorie row',
    ],
    notes: 'Great for lower-body endurance',
  },
  {
    name: 'EMOM Heavy Deadlift',
    type: 'EMOM',
    duration: 10,
    description: 'Strength under time constraint',
    movements: [
      'Odd minutes: 3 Heavy Deadlifts (102/70 kg)',
      'Even minutes: 8 Burpees',
    ],
    notes: 'Good for quality strength + metcon',
  },
  {
    name: 'Tabata Full Body Meltdown',
    type: 'Tabata',
    duration: 32,
    description: 'Multiple Tabata stations',
    movements: [
      'Tabata x8: Jump Squats',
      'Tabata x8: Push-ups',
      'Tabata x8: Sit-ups',
      'Tabata x8: Mountain Climbers',
    ],
    notes: 'High intensity, minimal rest',
  },
  {
    name: 'Chipper 1000m + 1000 reps',
    type: 'Chipper',
    duration: 50,
    description: 'Big volume',
    movements: [
      '1000m Run',
      '250 Air Squats',
      '250 Sit-ups',
      '250 Push-ups',
      '250 Jump Rope (singles)',
    ],
    notes: 'Partition heavily',
  },
  {
    name: 'Mixed Modal AMRAP 25',
    type: 'AMRAP',
    duration: 25,
    description: 'Mixed modalities',
    movements: [
      '12 Kettlebell Swings (32/24 kg)',
      '9 Pull-ups',
      '6 Push-presses (43/29 kg)',
    ],
    notes: 'Balanced movement domains',
  },
  {
    name: '400m Repeat with Wall-Balls',
    type: 'Rounds',
    duration: 27,
    description: 'Repeated run + strength',
    movements: [
      '400m Run',
      '20 Wall-Balls (9/6 kg)',
    ],
    notes: 'Pace run to maintain quality',
  },
  {
    name: 'Gymnastic Ladder 1-2-3-4-5',
    type: 'For Time',
    duration: 15,
    description: 'Gymnastics intensive',
    movements: [
      '1-2-3-4-5 Ring Muscle-Ups (or pull-ups)',
      '1-2-3-4-5 Pistols (each leg)',
    ],
    notes: 'Use regressions for muscle-ups/pistols',
  },
  {
    name: 'Strength + Sprint Split',
    type: 'Custom',
    duration: 35,
    description: 'Build strength then sprint finish',
    movements: [
      'Part A: 15 min work up to 5RM Front Squat',
      'Part B: For time: 8 rounds: 100m Sprint, 10 Burpees',
    ],
    notes: 'Good two-phase workout',
  },
  {
    name: 'Partner EMOM Go/Rest',
    type: 'Custom',
    duration: 20,
    description: 'Alternating partner EMOM for 20 minutes',
    movements: [
      'Every minute: Partner A does 10 Cal Row, Partner B rests; next minute swap',
      'After row, both do 5 Burpee Box Jumps',
    ],
    notes: 'Encourages team pacing',
  },
  {
    name: 'Ladder Up/Down 1-2-3-…-5-4-3-2-1',
    type: 'For Time',
    duration: 10,
    description: 'Combined up and down ladder',
    movements: [
      '1-2-3-4-5-4-3-2-1 Thrusters (20/16 kg)',
      '1-2-3-4-5-4-3-2-1 Burpees',
    ],
    notes: 'Good quick WOD',
  },
  {
    name: '30-min AMRAP Heavy/Light Mix',
    type: 'AMRAP',
    duration: 30,
    description: 'Longish mixed WOD',
    movements: [
      '10 Deadlifts (84/61 kg)',
      '15 Box Jumps (61/51 cm)',
      '20 Sit-ups',
    ],
    notes: 'Manage pace so full time used',
  },
  {
    name: 'Sled Push & Shuttle Run',
    type: 'For Time',
    duration: 25,
    description: 'Strongman & cardio mix',
    movements: [
      '4×30m Sled Push (heavy)',
      '4×100m Shuttle Run (4×25m with turn)',
    ],
    notes: 'Use manageable sled weight',
  },
  {
    name: 'Bike/Burpee Alternator',
    type: 'Rounds',
    duration: 18,
    description: 'Work/rest alternate cardio/strength',
    movements: [
      '12 Cal Bike',
      '8 Burpees',
    ],
    notes: 'Simple but effective',
  },
  {
    name: 'Tabata and AMRAP Hybrid',
    type: 'Custom',
    duration: 23,
    description: 'Tabata block then AMRAP',
    movements: [
      'Tabata x8: Air Squats',
      'Then 12-min AMRAP: 10 Push-press (29/20 kg), 15 Sit-ups',
    ],
    notes: 'Good mix of short intense + moderate',
  },
  {
    name: '50-40-30-20-10 KB/Bodyweight',
    type: 'For Time',
    duration: 25,
    description: 'Big descending rep chipper',
    movements: [
      '50-40-30-20-10 KB Swings (24/16 kg)',
      '50-40-30-20-10 Walking Lunges (each leg count=1)',
      '50-40-30-20-10 Burpees',
    ],
    notes: 'Scale KB weight appropriately',
  },
  {
    name: 'Endurance AMRAP 40',
    type: 'AMRAP',
    duration: 40,
    description: '40-minute long endurance AMRAP (long)',
    movements: [
      '400m Run',
      '25 Air Squats',
      '10 Pull-ups',
    ],
    notes: 'Pace sustainable, scale pull-ups to ring rows',
  },
  {
    name: 'Heavy Clean Ladder + Burpees',
    type: 'For Time',
    duration: 20,
    description: 'Builds strength + conditioning',
    movements: [
      'Clean ladder 1-5 (1+2+3+4+5) at 70% 1RM',
      'After each ladder set do 10 Burpees',
    ],
    notes: 'Good for improving cleans under fatigue',
  },
  {
    name: 'Core Crusher Tabata',
    type: 'Tabata',
    duration: 24,
    description: 'Core-heavy Tabata',
    movements: [
      'Tabata x8: Plank hold',
      'Tabata x8: V-ups',
      'Tabata x8: Russian Twists (11/7 kg)',
    ],
    notes: 'Focus on form',
  },
  {
    name: 'Mixed Modal 20-10 AMRAP',
    type: 'AMRAP',
    duration: 20,
    description: 'Short intense work: 20 minutes AMRAP',
    movements: [
      '20 Cal Row',
      '15 KB Swings (32/24 kg)',
      '10 Pull-ups',
    ],
    notes: 'Choose weight to manage sets',
  },
  {
    name: 'Gymnastic & Sprint Chipper',
    type: 'Chipper',
    duration: 30,
    description: 'Gymnastics heavy with sprint',
    movements: [
      '800m Run',
      '50 Toes-to-Bar (or hanging knee raises)',
      '40 Hand-stand hold secs',
      '30 Pistols (each leg)',
      '20 Burpees',
    ],
    notes: 'Scale gymnastics to progressions',
  },
  {
    name: 'EMOM Power Snatch & Box Jump',
    type: 'EMOM',
    duration: 12,
    description: 'Technical plus plyo',
    movements: [
      'Odd minutes: 4 Power Snatches (34/25 kg)',
      'Even minutes: 6 Box Jumps (76/61 cm)',
    ],
    notes: 'Use moderate weight to perfect form',
  },
  {
    name: 'Chipper 100/90/80',
    type: 'For Time',
    duration: 23,
    description: 'Descending rep chipper',
    movements: [
      '100-90-80 Calories Bike',
      '100-90-80 Wall-Balls (9/6 kg)',
      '100-90-80 Sit-ups',
    ],
    notes: 'Good for moderate equipment',
  },
  {
    name: 'Partner Synchronized Complex',
    type: 'Custom',
    duration: 18,
    description: 'Partners move together through heavy complex',
    movements: [
      '7 synchronized rounds: Barbell Complex: Power Clean, Front Squat, Push-press, Back Squat, Push-press (61/43 kg)',
    ],
    notes: 'From partner workout list',
  },
  {
    name: 'Walking Lunges + Row Repeats',
    type: 'Rounds',
    duration: 25,
    description: 'Alternating carry & row',
    movements: [
      '200m Walking Lunges (each step count 1)',
      '250m Row',
    ],
    notes: 'Good for leg endurance and cardio',
  },
  {
    name: 'Tabata Upper Body',
    type: 'Tabata',
    duration: 32,
    description: 'Upper body focus',
    movements: [
      'Tabata x8: Push-ups',
      'Tabata x8: Ring Rows',
      'Tabata x8: Shoulder Taps',
      'Tabata x8: Burpees',
    ],
    notes: 'High intensity, limited rest',
  },
  {
    name: '400m Run Chipper',
    type: 'For Time',
    duration: 25,
    description: 'Repeated run + strength',
    movements: [
      '400m Run',
      '25 Air Squats',
      '15 Push-press (29/20 kg)',
    ],
    notes: 'From home/regular gym style list',
  },
  {
    name: 'EMOM Skill + Sprint',
    type: 'EMOM',
    duration: 16,
    description: 'Skill practice plus sprint intervals',
    movements: [
      'Odd minutes: 1 min Handstand Hold or Practice',
      'Even minutes: 100m Sprint',
    ],
    notes: 'Good for gymnastics & explosiveness',
  },
  {
    name: 'Endurance Run & Bodyweight',
    type: 'For Time',
    duration: 35,
    description: 'Longer duration endurance WOD',
    movements: [
      '1 mile Run',
      '50 Pull-ups (or ring rows)',
      '100 Push-ups',
      '1 mile Run',
    ],
    notes: 'Scale pull-ups to rows',
  },
  {
    name: 'Lunges & Thrusters Descend',
    type: 'For Time',
    duration: 25,
    description: 'Strength + endurance',
    movements: [
      '50-40-30-20-10 Walking Lunges (each leg count=1)',
      '50-40-30-20-10 Thrusters (20/16 kg)',
    ],
    notes: 'Good for legs and full body',
  },
  {
    name: '30-min AMRAP Legs/Chest/Core',
    type: 'AMRAP',
    duration: 30,
    description: '30-minute long mixed body part WOD (long)',
    movements: [
      '10 Back Squats (52/34 kg)',
      '15 Push-ups',
      '20 Sit-ups',
    ],
    notes: 'Sustainable pacing important',
  },
  {
    name: 'Tabata Sprint & Bodyweight',
    type: 'Tabata',
    duration: 25,
    description: 'Core cardio mixed Tabata',
    movements: [
      'Tabata x8: 200m Sprint (or 30s all-out)',
      'Tabata x8: Air Squats',
      'Tabata x8: Push-ups',
    ],
    notes: 'Max effort during on-periods',
  },

  // ========================================
  // ADDITIONAL WORKOUTS (50 more workouts - Barbell Focus)
  // ========================================

  {
    name: 'Barbell Inferno',
    type: 'For Time',
    duration: 10,
    description: 'Classic barbell cycling with decreasing reps',
    movements: [
      '21-15-9 Power Cleans (61/43 kg)',
      '21-15-9 Bar-Facing Burpees',
    ],
    notes: 'Keep barbell touch-and-go if possible',
  },
  {
    name: 'Iron Annie',
    type: 'For Time',
    duration: 13,
    description: 'Annie-style ladder meets barbell complex',
    movements: [
      '50 Double Unders',
      '15 Deadlifts (102/70 kg)',
      '40 Double Unders',
      '12 Hang Power Cleans (70/48 kg)',
      '30 Double Unders',
      '9 Push Jerks (61/43 kg)',
    ],
    notes: 'Annie-style ladder meets barbell complex',
  },
  {
    name: 'Barbell Battery',
    type: 'EMOM',
    duration: 18,
    description: 'EMOM 18 - heavy barbell cycling',
    movements: [
      'Minute 1: 5 Deadlifts (125/84 kg)',
      'Minute 2: 7 Front Squats (84/57 kg)',
      'Minute 3: 9 Push Press (61/43 kg)',
    ],
    notes: 'Goal: unbroken reps, consistent tempo',
  },
  {
    name: 'Full Metal Grace',
    type: 'For Time',
    duration: 5,
    description: 'Classic benchmark variation—focus on cycling efficiency',
    movements: [
      '30 Clean and Jerks (61/43 kg)',
    ],
    notes: 'Classic benchmark variation—focus on cycling efficiency. Sub-5 min goal',
  },
  {
    name: 'The Complex',
    type: 'Custom',
    duration: 45,
    description: 'Barbell complex for load',
    movements: [
      '7 Rounds for Load:',
      '1 Deadlift',
      '1 Hang Power Clean',
      '1 Front Squat',
      '1 Push Press',
      '1 Back Squat',
      '1 Behind-the-Neck Push Press',
    ],
    notes: 'Rest 2 min between rounds. Score = heaviest unbroken complex',
  },
  {
    name: 'Press Factory',
    type: 'EMOM',
    duration: 20,
    description: 'Upper body fatigue management',
    movements: [
      'Alternate every minute:',
      '3 Push Press (61/43 kg)',
      '5 Handstand Push-ups',
    ],
    notes: 'Upper body fatigue management',
  },
  {
    name: 'Hang On',
    type: 'Rounds',
    duration: 18,
    description: 'Grip test + stability challenge',
    movements: [
      '10 Hang Power Snatches (43/29 kg)',
      '10 Overhead Squats (same bar)',
      '10 Toes-to-Bar',
    ],
    notes: 'Grip test + stability challenge. 5 rounds for time',
  },
  {
    name: 'The Grinder',
    type: 'AMRAP',
    duration: 30,
    description: 'Moderate weight; sustainable pacing',
    movements: [
      '10 Deadlifts (84/57 kg)',
      '10 Barbell Step-ups (20/16 kg bar)',
      '400m Run',
    ],
    notes: 'Moderate weight; sustainable pacing',
  },
  {
    name: 'Barbell Ladders',
    type: 'For Time',
    duration: 20,
    description: 'Ladder 1–10–1',
    movements: [
      'Power Clean + Jerk (70/48 kg)',
      'Add one rep per round up to 10, then descend back to 1',
    ],
    notes: 'Add one rep per round up to 10, then descend back to 1',
  },
  {
    name: 'Heavy DT',
    type: 'For Time',
    duration: 10,
    description: 'Keep barbell unbroken as long as possible',
    movements: [
      '12 Deadlifts (70/48 kg)',
      '9 Hang Power Cleans (70/48 kg)',
      '6 Push Jerks (70/48 kg)',
    ],
    notes: 'Keep barbell unbroken as long as possible',
  },
  {
    name: 'Death by Clean',
    type: 'EMOM',
    duration: 15,
    description: 'EMOM until failure',
    movements: [
      'Minute 1: 1 Clean (84/57 kg)',
      'Minute 2: 2 Cleans',
      '(Continue adding 1 clean each minute until failure)',
    ],
    notes: 'Use full cleans, not power',
  },
  {
    name: 'Barbell & Bike',
    type: 'For Time',
    duration: 15,
    description: 'Unbroken barbell = key',
    movements: [
      '15 Cal Bike',
      '10 Front Squats (61/43 kg)',
      '5 Push Jerks (61/43 kg)',
    ],
    notes: 'Unbroken barbell = key',
  },
  {
    name: 'Power Trip',
    type: 'For Time',
    duration: 18,
    description: 'High volume snatch cycling',
    movements: [
      '21-18-15-12-9-6-3 Power Snatches (43/29 kg)',
    ],
    notes: 'High volume snatch cycling',
  },
  {
    name: 'Heavy Grace',
    type: 'For Time',
    duration: 8,
    description: 'Advanced version of Grace',
    movements: [
      '30 Clean and Jerks (84/57 kg)',
    ],
    notes: 'Advanced version of Grace',
  },
  {
    name: 'Barbell Hell',
    type: 'Rounds',
    duration: 23,
    description: 'Drop weight between moves—cycling endurance test',
    movements: [
      '10 Deadlifts (102/70 kg)',
      '10 Power Cleans (70/48 kg)',
      '10 Front Squats (61/43 kg)',
      '10 Push Jerks (52/34 kg)',
    ],
    notes: 'Drop weight between moves—cycling endurance test. 4 rounds for time',
  },
  {
    name: 'The Mountain',
    type: 'For Time',
    duration: 25,
    description: 'Ladder Up 1–10',
    movements: [
      '1-10 Reps: Thrusters (43/29 kg)',
      'After each set: 10 Pull-ups',
    ],
    notes: 'Builds exponentially',
  },
  {
    name: 'Squatstorm',
    type: 'For Time',
    duration: 15,
    description: 'Mobility and shoulder endurance',
    movements: [
      '10 Overhead Squats (61/43 kg)',
      '20 Wall Balls (9/6 kg)',
    ],
    notes: 'Mobility and shoulder endurance',
  },
  {
    name: 'Barbell Biathlon',
    type: 'Custom',
    duration: 25,
    description: 'High-intensity intervals',
    movements: [
      '400m Run',
      '10 Barbell Thrusters (52/34 kg)',
    ],
    notes: 'High-intensity intervals. 3 rounds, rest 2 min between rounds',
  },
  {
    name: 'Push/Pull 21-15-9',
    type: 'For Time',
    duration: 15,
    description: 'Classic power combo',
    movements: [
      '21-15-9 Deadlifts (102/70 kg)',
      '21-15-9 Handstand Push-ups',
    ],
    notes: 'Classic power combo',
  },
  {
    name: 'Oly Grinder',
    type: 'AMRAP',
    duration: 25,
    description: 'Keep snatches unbroken',
    movements: [
      '5 Power Snatches (52/34 kg)',
      '10 Front Squats (70/48 kg)',
      '15 Cal Row',
    ],
    notes: 'Keep snatches unbroken',
  },
  {
    name: 'Cycle of Pain',
    type: 'EMOM',
    duration: 16,
    description: 'All unbroken, touch-and-go',
    movements: [
      '4 Power Cleans (84/57 kg)',
      '4 Front Squats',
      '4 Push Jerks',
    ],
    notes: 'All unbroken, touch-and-go',
  },
  {
    name: 'Barbell Chief',
    type: 'Custom',
    duration: 20,
    description: '5 x 3-min AMRAPs',
    movements: [
      '3 Power Cleans (61/43 kg)',
      '6 Push-ups',
      '9 Air Squats',
      '(Rest 1 min between rounds)',
    ],
    notes: 'Inspired by Chief, heavier cycling',
  },
  {
    name: 'Snatch Ladder 10:1',
    type: 'For Time',
    duration: 18,
    description: 'Work inverse ladder pacing',
    movements: [
      '10-1 Power Snatches (52/34 kg)',
      '1-10 Burpees',
    ],
    notes: 'Work inverse ladder pacing',
  },
  {
    name: 'Double DT',
    type: 'For Time',
    duration: 25,
    description: 'True test of endurance and grip',
    movements: [
      '10 Rounds of DT (same rep scheme as normal)',
      '12 Deadlifts (70/48 kg)',
      '9 Hang Power Cleans (70/48 kg)',
      '6 Push Jerks (70/48 kg)',
    ],
    notes: 'True test of endurance and grip',
  },
  {
    name: 'Barbell Karen',
    type: 'For Time',
    duration: 20,
    description: 'Sub for wall balls—light barbell endurance',
    movements: [
      '150 Thrusters (29/20 kg)',
    ],
    notes: 'Sub for wall balls—light barbell endurance',
  },
  {
    name: 'Iron Horse',
    type: 'Rounds',
    duration: 22,
    description: 'Heavy, descending complex',
    movements: [
      '400m Run',
      '12 Deadlifts (102/70 kg)',
      '9 Hang Cleans (61/43 kg)',
      '6 Push Jerks (52/34 kg)',
    ],
    notes: 'Heavy, descending complex. 3 rounds for time',
  },
  {
    name: 'Grip Reaper',
    type: 'For Time',
    duration: 20,
    description: 'Grip management workout',
    movements: [
      '50 Hang Power Cleans (43/29 kg)',
      'Every 2 min: 5 Toes-to-Bar',
    ],
    notes: 'Grip management workout',
  },
  {
    name: 'Thruster Pyramid',
    type: 'For Time',
    duration: 16,
    description: 'Ladder 10-9-8-…-1',
    movements: [
      '10-9-8-7-6-5-4-3-2-1 Thrusters (43/29 kg)',
      '10-9-8-7-6-5-4-3-2-1 Bar-Facing Burpees',
    ],
    notes: 'Burnout finisher',
  },
  {
    name: 'Death by Thrusters',
    type: 'EMOM',
    duration: 15,
    description: 'EMOM Until Failure',
    movements: [
      'Minute 1: 1 Thruster (43/29 kg)',
      'Minute 2: 2 Thrusters',
      '(Continue adding 1 thruster each minute until failure)',
    ],
    notes: 'Go until you fail the minute',
  },
  {
    name: 'Heavy Isabel',
    type: 'For Time',
    duration: 8,
    description: 'Go touch-and-go or singles depending on ability',
    movements: [
      '30 Snatches (61/43 kg)',
    ],
    notes: 'Go touch-and-go or singles depending on ability',
  },
  {
    name: 'The Mule',
    type: 'For Time',
    duration: 18,
    description: 'Heavy and simple',
    movements: [
      '21-15-9 Deadlifts (143/102 kg)',
      '21-15-9 Burpee Pull-ups',
    ],
    notes: 'Heavy and simple',
  },
  {
    name: 'Iron Curtain',
    type: 'For Time',
    duration: 20,
    description: 'Unbroken barbell focus',
    movements: [
      '10 Power Cleans (70/48 kg)',
      '10 Front Rack Lunges',
      '10 Push Jerks',
    ],
    notes: 'Unbroken barbell focus',
  },
  {
    name: 'Barbell Triathlon',
    type: 'Custom',
    duration: 40,
    description: 'Rest as needed; partition as you like',
    movements: [
      '100 Deadlifts (61/43 kg)',
      '75 Hang Power Cleans (43/29 kg)',
      '50 Shoulder-to-Overhead (43/29 kg)',
    ],
    notes: 'Rest as needed; partition as you like',
  },
  {
    name: 'The Grit Set',
    type: 'For Time',
    duration: 12,
    description: 'Unbroken for elite',
    movements: [
      '21 Front Squats (61/43 kg)',
      '15 Hang Cleans (61/43 kg)',
      '9 Push Jerks (61/43 kg)',
    ],
    notes: 'Unbroken for elite',
  },
  {
    name: 'Tempo DT',
    type: 'For Time',
    duration: 25,
    description: '3-sec eccentric on all lifts',
    movements: [
      '12 Deadlifts (70/48 kg)',
      '9 Hang Power Cleans (70/48 kg)',
      '6 Push Jerks (70/48 kg)',
    ],
    notes: 'Slows DT down, builds control and fatigue resistance. 3-sec eccentric on all lifts',
  },
  {
    name: 'Barbell Betty',
    type: 'Rounds',
    duration: 18,
    description: 'Barbell complex variation',
    movements: [
      '12 Deadlifts (70/48 kg)',
      '9 Hang Power Snatches (43/29 kg)',
      '6 Push Jerks (61/43 kg)',
    ],
    notes: 'Barbell complex variation. 5 rounds for time',
  },
  {
    name: 'Shoulder Factory',
    type: 'EMOM',
    duration: 15,
    description: 'Hypertrophy + strength endurance',
    movements: [
      '5 Push Jerks (61/43 kg)',
      '10 Dumbbell Front Raises (mod)',
    ],
    notes: 'Hypertrophy + strength endurance',
  },
  {
    name: 'Barbell Box',
    type: 'Rounds',
    duration: 18,
    description: 'Legs + lungs combo',
    movements: [
      '10 Front Squats (61/43 kg)',
      '15 Box Jumps (61/51 cm)',
    ],
    notes: 'Legs + lungs combo. 6 rounds for time',
  },
  {
    name: 'Cleanstorm',
    type: 'For Time',
    duration: 15,
    description: 'Heavy touch-and-go',
    movements: [
      '10-8-6-4-2 Cleans (102/70 kg)',
      '20 Double-Unders after each round',
    ],
    notes: 'Heavy touch-and-go',
  },
  {
    name: 'Power Surge',
    type: 'AMRAP',
    duration: 12,
    description: 'Light barbell, high turnover',
    movements: [
      '6 Power Snatches (43/29 kg)',
      '9 Thrusters (43/29 kg)',
      '12 Cal Row',
    ],
    notes: 'Light barbell, high turnover',
  },
  {
    name: 'Barbell Bodyweight Mix AMRAP',
    type: 'AMRAP',
    duration: 20,
    description: 'Barbell and bodyweight combination AMRAP',
    movements: [
      '5 Deadlifts (70/48 kg)',
      '10 Push-ups',
      '15 Air Squats',
    ],
    notes: 'Barbell and bodyweight combination',
  },
  {
    name: 'Barbell 40',
    type: 'For Time',
    duration: 20,
    description: 'Split as needed, steady tempo',
    movements: [
      '40 Power Cleans (61/43 kg)',
      '40 Overhead Squats (43/29 kg)',
    ],
    notes: 'Split as needed, steady tempo',
  },
  {
    name: 'Olympic Ladder',
    type: 'EMOM',
    duration: 12,
    description: 'Add weight each round',
    movements: [
      '1 Snatch + 1 Clean + 1 Jerk @ 70–85%',
    ],
    notes: 'Add weight each round',
  },
  {
    name: 'Barbell Tabata',
    type: 'Tabata',
    duration: 12,
    description: 'Switch every 4 min',
    movements: [
      'Tabata x8: Thrusters (29/20 kg)',
      'Tabata x8: Hang Cleans (43/29 kg)',
      'Tabata x8: Push Jerks (52/34 kg)',
    ],
    notes: 'Switch every 4 min',
  },
  {
    name: 'Iron Engine',
    type: 'AMRAP',
    duration: 40,
    description: 'Long endurance barbell metcon',
    movements: [
      '400m Run',
      '10 Deadlifts (84/57 kg)',
      '15 Wall Balls',
    ],
    notes: 'Long endurance barbell metcon',
  },
  {
    name: 'Barbell Bear',
    type: 'Custom',
    duration: 25,
    description: 'Bear Complex variation',
    movements: [
      '7 Sets (unbroken, 1 min rest) of:',
      '1 Power Clean',
      '1 Front Squat',
      '1 Push Press',
      '1 Back Squat',
      '1 Push Press',
    ],
    notes: 'Bear Complex variation',
  },
  {
    name: 'Frontline',
    type: 'Rounds',
    duration: 20,
    description: 'Classic strength metcon',
    movements: [
      '12 Front Squats (84/57 kg)',
      '10 Pull-ups',
      '8 Push Press (61/43 kg)',
    ],
    notes: 'Classic strength metcon. 4 rounds for time',
  },
  {
    name: 'Heavy Grace + Run',
    type: 'For Time',
    duration: 15,
    description: 'Combo test of power and cardio',
    movements: [
      '30 Clean & Jerks (84/57 kg)',
      '800m Run',
    ],
    notes: 'Combo test of power and cardio',
  },
  {
    name: 'Death March',
    type: 'EMOM',
    duration: 15,
    description: 'Posterior chain focus',
    movements: [
      'Odd minutes: 8 Deadlifts (102/70 kg)',
      'Even minutes: 12 Walking Lunges (43/29 kg, front rack)',
    ],
    notes: 'Posterior chain focus',
  },
  {
    name: 'Barbell Symphony',
    type: 'For Time',
    duration: 25,
    description: 'One of each lift; classic finale',
    movements: [
      '10 Snatches (52/34 kg)',
      '20 Cleans (61/43 kg)',
      '30 Front Squats (61/43 kg)',
      '40 Push Press (52/34 kg)',
    ],
    notes: 'One of each lift; classic finale',
  },
  {
    name: 'Barbell + Row EMOM',
    type: 'EMOM',
    duration: 40,
    description: 'Heavy strength + cardio',
    movements: [
      'Minute 1: 8 Deadlifts (102/70 kg)',
      'Minute 2: 12-15 Calories Row',
      'Alternate for 40 minutes (20 rounds each)',
    ],
    notes: 'Heavy strength + cardio',
  },
  {
    name: 'Gymnastics Skill EMOM',
    type: 'EMOM',
    duration: 40,
    description: 'Skill + volume',
    movements: [
      'Minute 1: 6 Ring Muscle-Up attempts (or 8 Pull-ups)',
      'Minute 2: 10 Toes-to-Bar',
      'Alternate 20 rounds (40 minutes)',
    ],
    notes: 'Skill + volume',
  },
  {
    name: 'Power Clean EMOM',
    type: 'EMOM',
    duration: 40,
    description: 'Barbell cycling + bodyweight',
    movements: [
      'Every minute: 3 Power Cleans (84/57 kg) + 6 Push-ups',
      'Do for 40 rounds (40 min)',
    ],
    notes: 'Barbell cycling + bodyweight',
  },
  {
    name: 'Bike + Thruster EMOM',
    type: 'EMOM',
    duration: 40,
    description: 'Conditioning + full-body',
    movements: [
      'Minute odd: 14 Calories Assault Bike',
      'Minute even: 8 Thrusters (43/29 kg)',
      'Total 40 minutes',
    ],
    notes: 'Conditioning + full-body',
  },
  {
    name: 'Snatch Cycle EMOM',
    type: 'EMOM',
    duration: 40,
    description: 'Technique under fatigue',
    movements: [
      'Every minute: 2 Snatches (52/34 kg) + 4 Overhead Squats (same bar)',
      '40 rounds',
    ],
    notes: 'Technique under fatigue',
  },
  {
    name: 'Clean & Jerk EMOM',
    type: 'EMOM',
    duration: 40,
    description: 'Mix heavy lift + plyo',
    movements: [
      'Minute 1: 2 Clean & Jerks (61/43 kg)',
      'Minute 2: 12 Box Jumps (61/51 cm)',
      'Alternate for 40 min',
    ],
    notes: 'Mix heavy lift + plyo',
  },
  {
    name: 'Wall Ball + Burpee EMOM',
    type: 'EMOM',
    duration: 40,
    description: 'High-tempo, minimal equipment',
    movements: [
      'Minute 1: 10 Wall Balls (9/6 kg)',
      'Minute 2: 8 Burpee-Box Jump Overs',
      'Alternate 20 rounds',
    ],
    notes: 'High-tempo, minimal equipment',
  },
  {
    name: 'Pull + Push EMOM',
    type: 'EMOM',
    duration: 40,
    description: 'Upper-body balanced',
    movements: [
      'Minute 1: 8 Chest-to-Bar Pull-ups',
      'Minute 2: 10 Push Press (52/34 kg)',
      'Alternate 20 rounds',
    ],
    notes: 'Upper-body balanced',
  },
  {
    name: 'GHD + Bike EMOM',
    type: 'EMOM',
    duration: 40,
    description: 'Core + cardio',
    movements: [
      'Minute 1: 12 GHD Sit-ups',
      'Minute 2: 15 Calories Ski-Erg',
      'Alternate 20 rounds',
    ],
    notes: 'Core + cardio',
  },
  {
    name: 'Front Squat EMOM',
    type: 'EMOM',
    duration: 40,
    description: 'Pure strength endurance',
    movements: [
      'Every minute: 5 Front Squats (70/48 kg)',
      'For 40 minutes',
    ],
    notes: 'Pure strength endurance',
  },
  {
    name: 'Deadlift + Cal Row EMOM',
    type: 'EMOM',
    duration: 40,
    description: 'Posterior chain + conditioning',
    movements: [
      'Minute odd: 5 Deadlifts (120/84 kg)',
      'Minute even: 10 Calories Row',
      'Alternate 20 rounds',
    ],
    notes: 'Posterior chain + conditioning',
  },
  {
    name: 'Muscle-Up + Lunge EMOM',
    type: 'EMOM',
    duration: 40,
    description: 'Gymnastics + legs',
    movements: [
      'Minute 1: 4 Bar Muscle-Ups (or 6 Ring Rows)',
      'Minute 2: 12 Walking Lunges (each leg) (barbell front rack optional)',
      'Alternate 20 rounds',
    ],
    notes: 'Gymnastics + legs',
  },
  {
    name: 'Overhead Squat EMOM',
    type: 'EMOM',
    duration: 40,
    description: 'Shoulder/leg endurance',
    movements: [
      'Every minute: 4 Overhead Squats (52/34 kg) + 6 Burpees',
      'For 40 minutes',
    ],
    notes: 'Shoulder/leg endurance',
  },
  {
    name: 'Thruster + Double-Under EMOM',
    type: 'EMOM',
    duration: 40,
    description: 'Mixed modalities',
    movements: [
      'Minute 1: 8 Thrusters (43/29 kg)',
      'Minute 2: 50 Double-unders (or 100 singles)',
      'Alternate 20 rounds',
    ],
    notes: 'Mixed modalities',
  },
  {
    name: 'Clean Ladder EMOM',
    type: 'EMOM',
    duration: 20,
    description: 'Progressive load, self-paced',
    movements: [
      'Every minute: 1 more Clean than previous minute (start at 1) until minute ~10, then reduce by 1 for remainder to 20 rounds',
      'Use ~61/43 kg',
    ],
    notes: 'Progressive load, self-paced',
  },
  {
    name: 'Sled Push + Pull-up EMOM',
    type: 'EMOM',
    duration: 40,
    description: 'Full-body big effort',
    movements: [
      'Minute 1: 30m Sled Push (heavy)',
      'Minute 2: 10 Pull-ups',
      'Alternate 20 rounds',
    ],
    notes: 'Full-body big effort',
  },
  {
    name: 'Handstand + Press EMOM',
    type: 'EMOM',
    duration: 40,
    description: 'Gymnastics + weight',
    movements: [
      'Minute 1: 60s Handstand Hold or Handstand Push-ups (max reps)',
      'Minute 2: 8 Push Jerk (52/34 kg)',
      'Alternate 20 rounds',
    ],
    notes: 'Gymnastics + weight',
  },
  {
    name: 'Back Squat EMOM',
    type: 'EMOM',
    duration: 40,
    description: 'Strength + core',
    movements: [
      'Every minute: 5 Back Squats (84/57 kg) + 8 Sit-ups',
      'For 40 minutes',
    ],
    notes: 'Strength + core',
  },
  {
    name: 'Snatch + Wall Walk EMOM',
    type: 'EMOM',
    duration: 40,
    description: 'Technique + conditioning',
    movements: [
      'Minute 1: 3 Power Snatches (43/29 kg)',
      'Minute 2: 6 Wall Walks + 6 V-ups',
      'Alternate 20 rounds',
    ],
    notes: 'Technique + conditioning',
  },
  {
    name: 'Bike Sprint + Kettlebell EMOM',
    type: 'EMOM',
    duration: 40,
    description: 'Two-movement combo',
    movements: [
      'Minute 1: 15 Calories Bike',
      'Minute 2: 12 KB Swings (32/24 kg)',
      'Alternate 20 rounds',
    ],
    notes: 'Two-movement combo',
  },
  {
    name: 'Clean & Front Squat EMOM',
    type: 'EMOM',
    duration: 40,
    description: 'Olympic lift plus strength',
    movements: [
      'Minute 1: 3 Clean (61/43 kg)',
      'Minute 2: 6 Front Squats (61/43 kg)',
      'Alternate 20 rounds',
    ],
    notes: 'Olympic lift plus strength',
  },
  {
    name: 'Ring Dip + Deadlift EMOM',
    type: 'EMOM',
    duration: 40,
    description: 'Upper body + posterior',
    movements: [
      'Minute 1: 10 Ring Dips',
      'Minute 2: 5 Deadlifts (102/70 kg)',
      'Alternate 20 rounds',
    ],
    notes: 'Upper body + posterior',
  },
  {
    name: 'Box Jump + Thruster EMOM',
    type: 'EMOM',
    duration: 40,
    description: 'Plyo + strength',
    movements: [
      'Minute 1: 12 Box Jumps (61/51 cm)',
      'Minute 2: 8 Thrusters (52/34 kg)',
      'Alternate 20 rounds',
    ],
    notes: 'Plyo + strength',
  },
  {
    name: 'Row + Clean & Jerk EMOM',
    type: 'EMOM',
    duration: 40,
    description: 'Cardio + barbell',
    movements: [
      'Minute 1: 12 Calories Row',
      'Minute 2: 3 Clean & Jerks (61/43 kg)',
      'Alternate 20 rounds',
    ],
    notes: 'Cardio + barbell',
  },
  {
    name: 'Overhead Walk + Pull EMOM',
    type: 'EMOM',
    duration: 40,
    description: 'Stability + gymnastics',
    movements: [
      'Minute 1: 30m Overhead Walk with barbell (43/29 kg)',
      'Minute 2: 8 Chest-to-Bar Pull-ups',
      'Alternate 20 rounds',
    ],
    notes: 'Stability + gymnastics',
  },
  {
    name: 'Thruster + L-Sit EMOM',
    type: 'EMOM',
    duration: 40,
    description: 'Full-body + core',
    movements: [
      'Minute 1: 8 Thrusters (43/29 kg)',
      'Minute 2: 30-sec L-Sit hold or 8 Toes-to-Bar',
      'Alternate 20 rounds',
    ],
    notes: 'Full-body + core',
  },
  {
    name: 'Deadlift + Sandbag Carry EMOM',
    type: 'EMOM',
    duration: 40,
    description: 'Strength + strongman',
    movements: [
      'Minute 1: 5 Deadlifts (125/84 kg)',
      'Minute 2: 30m Sandbag Carry (shoulder)',
      'Alternate 20 rounds',
    ],
    notes: 'Strength + strongman',
  },
  {
    name: 'Snatch Complex EMOM',
    type: 'EMOM',
    duration: 40,
    description: 'Technical, moderate weight',
    movements: [
      'Every minute: 1 Snatch + 1 Overhead Squat (43/29 kg)',
      'For 40 minutes',
    ],
    notes: 'Technical, moderate weight',
  },
  {
    name: 'Pull-up Ladder EMOM',
    type: 'EMOM',
    duration: 40,
    description: 'Gymnastics focus',
    movements: [
      'Minute 1: 3 Bar Muscle-Ups (or 5 Pull-ups)',
      'Minute 2: 6 Pull-ups',
      'Alternate 20 rounds',
    ],
    notes: 'Gymnastics focus',
  },
  {
    name: 'Back Rack Lunge + Push-Press EMOM',
    type: 'EMOM',
    duration: 40,
    description: 'Legs + shoulders',
    movements: [
      'Minute 1: 10 Back-Rack Lunges (each leg count=1) (43/29 kg)',
      'Minute 2: 8 Push Press (52/34 kg)',
      'Alternate 20 rounds',
    ],
    notes: 'Legs + shoulders',
  },
  {
    name: 'Assault Bike + Clean EMOM',
    type: 'EMOM',
    duration: 40,
    description: 'Conditioning + barbell',
    movements: [
      'Minute 1: 15 Calories Assault Bike',
      'Minute 2: 3 Cleans (61/43 kg)',
      'Alternate 20 rounds',
    ],
    notes: 'Conditioning + barbell',
  },
  {
    name: 'Overhead Squat + Burpee EMOM',
    type: 'EMOM',
    duration: 40,
    description: 'Shoulder + cardio',
    movements: [
      'Minute 1: 4 Overhead Squats (52/34 kg)',
      'Minute 2: 8 Burpees',
      'Alternate 20 rounds',
    ],
    notes: 'Shoulder + cardio',
  },
  {
    name: 'Front Rack Carry + Pull-ups EMOM',
    type: 'EMOM',
    duration: 40,
    description: 'Grip + upper body',
    movements: [
      'Minute 1: 40m Front Rack Carry (43/29 kg)',
      'Minute 2: 10 Pull-ups',
      'Alternate 20 rounds',
    ],
    notes: 'Grip + upper body',
  },
  {
    name: 'Thruster + Cal Row EMOM',
    type: 'EMOM',
    duration: 40,
    description: 'Strength + endurance',
    movements: [
      'Minute 1: 8 Thrusters (43/29 kg)',
      'Minute 2: 12 Calories Row',
      'Alternate 20 rounds',
    ],
    notes: 'Strength + endurance',
  },
  {
    name: 'Clean & Hang Power Clean EMOM',
    type: 'EMOM',
    duration: 40,
    description: 'Barbell cycling',
    movements: [
      'Every minute: 2 Cleans + 2 Hang Power Cleans (61/43 kg)',
      'For 40 minutes',
    ],
    notes: 'Barbell cycling',
  },
  {
    name: 'GHD Sit-up + Deadlift EMOM',
    type: 'EMOM',
    duration: 40,
    description: 'Core + heavy lift',
    movements: [
      'Minute 1: 15 GHD Sit-ups',
      'Minute 2: 5 Deadlifts (111/75 kg)',
      'Alternate 20 rounds',
    ],
    notes: 'Core + heavy lift',
  },
  {
    name: 'Ski-Erg + Overhead Press EMOM',
    type: 'EMOM',
    duration: 40,
    description: 'Conditioning + push strength',
    movements: [
      'Minute 1: 15 Calories Ski-Erg',
      'Minute 2: 8 Overhead Press (43/29 kg)',
      'Alternate 20 rounds',
    ],
    notes: 'Conditioning + push strength',
  },
  {
    name: 'Ring Muscle-Up + Wall Ball EMOM',
    type: 'EMOM',
    duration: 40,
    description: 'Gymnastic + high-rep',
    movements: [
      'Minute 1: 6 Ring Muscle-Ups (or 10 Ring Rows)',
      'Minute 2: 20 Wall Balls (9/6 kg)',
      'Alternate 20 rounds',
    ],
    notes: 'Gymnastic + high-rep',
  },
  {
    name: 'Back Squat + Double-Unders EMOM',
    type: 'EMOM',
    duration: 40,
    description: 'Leg strength + cardio',
    movements: [
      'Minute 1: 5 Back Squats (84/57 kg)',
      'Minute 2: 75 Double-unders (or 150 singles)',
      'Alternate 20 rounds',
    ],
    notes: 'Leg strength + cardio',
  },
  {
    name: 'Push Jerk + Box Step-up EMOM',
    type: 'EMOM',
    duration: 40,
    description: 'Upper body + lower body',
    movements: [
      'Minute 1: 6 Push Jerks (52/34 kg)',
      'Minute 2: 12 Box Step-ups (61/51 cm) with dumbbells (16/11 kg)',
      'Alternate 20 rounds',
    ],
    notes: 'Upper body + lower body',
  },
  {
    name: 'Clean + Thruster EMOM',
    type: 'EMOM',
    duration: 40,
    description: 'Barbell couplet',
    movements: [
      'Every minute: 2 Cleans + 6 Thrusters (43/29 kg)',
      'For 40 minutes',
    ],
    notes: 'Barbell couplet',
  },
  {
    name: 'Pull-up + Deadlift EMOM',
    type: 'EMOM',
    duration: 40,
    description: 'Upper + posterior chain',
    movements: [
      'Minute 1: 10 Chest-to-Bar Pull-ups',
      'Minute 2: 5 Deadlifts (120/84 kg)',
      'Alternate 20 rounds',
    ],
    notes: 'Upper + posterior chain',
  },
  {
    name: 'Handstand Walk + Clean & Jerk EMOM',
    type: 'EMOM',
    duration: 40,
    description: 'Skill + strength',
    movements: [
      'Minute 1: 20m Handstand Walk or 8 Handstand Push-ups',
      'Minute 2: 3 Clean & Jerks (61/43 kg)',
      'Alternate 20 rounds',
    ],
    notes: 'Skill + strength',
  },
  {
    name: 'KB/Barbell Complex EMOM',
    type: 'EMOM',
    duration: 40,
    description: 'Two-movement mix',
    movements: [
      'Minute 1: 8 KB Swings (32/24 kg)',
      'Minute 2: 5 Cleans (61/43 kg)',
      'Alternate 20 rounds',
    ],
    notes: 'Two-movement mix',
  },
  {
    name: 'Thruster + Pistols EMOM',
    type: 'EMOM',
    duration: 40,
    description: 'Full body + leg skill',
    movements: [
      'Minute 1: 8 Thrusters (43/29 kg)',
      'Minute 2: 8 Pistols (or Assisted Pistol Lunges) each leg',
      'Alternate 20 rounds',
    ],
    notes: 'Full body + leg skill',
  },
  {
    name: 'Front Squat + Cal Bike EMOM',
    type: 'EMOM',
    duration: 40,
    description: 'Strength + cardio',
    movements: [
      'Minute 1: 6 Front Squats (70/48 kg)',
      'Minute 2: 12 Calories Bike',
      'Alternate 20 rounds',
    ],
    notes: 'Strength + cardio',
  },
  {
    name: 'Barbell Row + Burpee EMOM',
    type: 'EMOM',
    duration: 40,
    description: 'Pull + cardio',
    movements: [
      'Minute 1: 8 Barbell Rows (61/43 kg)',
      'Minute 2: 10 Burpees',
      'Alternate 20 rounds',
    ],
    notes: 'Pull + cardio',
  },
  {
    name: 'Snatch + Box Jump EMOM',
    type: 'EMOM',
    duration: 40,
    description: 'Power + plyometric',
    movements: [
      'Minute 1: 2 Snatches (52/34 kg)',
      'Minute 2: 10 Box Jumps (61/51 cm)',
      'Alternate 20 rounds',
    ],
    notes: 'Power + plyometric',
  },
  {
    name: 'Push Press + GHD EMOM',
    type: 'EMOM',
    duration: 40,
    description: 'Upper strength + core',
    movements: [
      'Minute 1: 8 Push Press (52/34 kg)',
      'Minute 2: 12 GHD Sit-ups',
      'Alternate 20 rounds',
    ],
    notes: 'Upper strength + core',
  },
  {
    name: 'Clean & Jerk + Assault Bike EMOM',
    type: 'EMOM',
    duration: 40,
    description: 'Barbell + cardio high output',
    movements: [
      'Minute 1: 3 Clean & Jerks (61/43 kg)',
      'Minute 2: 14 Calories Assault Bike',
      'Alternate 20 rounds',
    ],
    notes: 'Barbell + cardio high output',
  },
  {
    name: 'Engine Builder',
    type: 'EMOM',
    duration: 40,
    description: 'Four-movement engine builder',
    movements: [
      'Minute 1: 12/10 Cal Row (scale: 10/8 Cal or 200/150 m)',
      'Minute 2: 10 Front Squats (52/34 kg; scale: 43/29 kg or air squats)',
      'Minute 3: 12 Box Jumps (61/51 cm; scale: 51/41 cm)',
      'Minute 4: 8 Toes-to-Bar (scale: hanging knee raises)',
    ],
    notes: 'Four-movement engine builder',
  },
  {
    name: 'Barbell Battery II',
    type: 'EMOM',
    duration: 40,
    description: 'Barbell cycling + conditioning',
    movements: [
      'Minute 1: 5 Power Cleans (84/57 kg; scale: 61/43 kg)',
      'Minute 2: 8 Push Jerks (61/43 kg; scale: 43/29 kg)',
      'Minute 3: 10 Bar-Facing Burpees (scale: step-over burpees)',
      'Minute 4: 12/10 Cal Bike (scale: 10/8 Cal)',
    ],
    notes: 'Barbell cycling + conditioning',
  },
  {
    name: 'Gymnastic Flow',
    type: 'EMOM',
    duration: 40,
    description: 'Gymnastics + cardio',
    movements: [
      'Minute 1: 6 Chest-to-Bar Pull-ups (scale: regular pull-ups or ring rows)',
      'Minute 2: 10 Handstand Push-ups (scale: pike push-ups)',
      'Minute 3: 15 Air Squats',
      'Minute 4: 12/10 Cal Row (scale: 10/8 Cal or 200/150 m)',
    ],
    notes: 'Gymnastics + cardio',
  },
  {
    name: 'Heavy Engine',
    type: 'EMOM',
    duration: 40,
    description: 'Heavy strength + conditioning',
    movements: [
      'Minute 1: 4 Deadlifts (143/102 kg; scale: 102/70 kg)',
      'Minute 2: 12/10 Cal Assault Bike (scale: 10/8 Cal)',
      'Minute 3: 8 Wall Balls (14/9 kg; scale: 9/6 kg)',
      'Minute 4: 10 Sit-ups',
    ],
    notes: 'Heavy strength + conditioning',
  },
  {
    name: 'Grip Reaper II',
    type: 'EMOM',
    duration: 40,
    description: 'Grip strength + conditioning',
    movements: [
      'Minute 1: 8 Hang Power Cleans (61/43 kg; scale: 43/29 kg)',
      'Minute 2: 10 Toes-to-Bar (scale: hanging knee raises)',
      'Minute 3: 12 Kettlebell Swings (32/24 kg; scale: 24/16 kg)',
      'Minute 4: 14/12 Cal Row (scale: 10/8 Cal or 200/150 m)',
    ],
    notes: 'Grip strength + conditioning',
  },
  {
    name: 'Push Power',
    type: 'EMOM',
    duration: 40,
    description: 'Upper body power + conditioning',
    movements: [
      'Minute 1: 8 Push Press (61/43 kg; scale: 43/29 kg)',
      'Minute 2: 12 Burpees (scale: step-back burpees)',
      'Minute 3: 10 Wall Balls (9/6 kg; scale: 6/5 kg)',
      'Minute 4: 12/10 Cal Bike (scale: 10/8 Cal)',
    ],
    notes: 'Upper body power + conditioning',
  },
  {
    name: 'Classic HWPO Flow',
    type: 'EMOM',
    duration: 40,
    description: 'Classic HWPO-style EMOM',
    movements: [
      'Minute 1: 3 Clean & Jerks (84/57 kg; scale: 61/43 kg)',
      'Minute 2: 12 Box Step-ups (61/51 cm; scale: 51/41 cm)',
      'Minute 3: 10 Toes-to-Bar (scale: hanging knee raises)',
      'Minute 4: 15/12 Cal Row (scale: 12/10 Cal)',
    ],
    notes: 'Classic HWPO-style EMOM',
  },
  {
    name: 'Oly Grind',
    type: 'EMOM',
    duration: 40,
    description: 'Olympic lifting + conditioning',
    movements: [
      'Minute 1: 2 Power Snatches (61/43 kg; scale: 43/29 kg)',
      'Minute 2: 6 Overhead Squats (43/29 kg; scale: 29/20 kg)',
      'Minute 3: 12/10 Cal Ski (scale: 10/8 Cal or 200/150 m)',
      'Minute 4: 12 Sit-ups',
    ],
    notes: 'Olympic lifting + conditioning',
  },
  {
    name: 'Quadzilla',
    type: 'EMOM',
    duration: 40,
    description: 'Leg-focused strength + conditioning',
    movements: [
      'Minute 1: 10 Front Squats (61/43 kg; scale: 43/29 kg)',
      'Minute 2: 10 Lunges (each leg, front rack 43/29 kg; scale: bodyweight)',
      'Minute 3: 12/10 Cal Bike (scale: 10/8 Cal)',
      'Minute 4: 15 Air Squats',
    ],
    notes: 'Leg-focused strength + conditioning',
  },
  {
    name: 'Shoulder Storm',
    type: 'EMOM',
    duration: 40,
    description: 'Shoulder strength + conditioning',
    movements: [
      'Minute 1: 8 Push Jerks (52/34 kg; scale: 43/29 kg)',
      'Minute 2: 12 Dumbbell Front Raises (9/7 kg; scale: 7/5 kg)',
      'Minute 3: 10 Wall Walks (scale: 6 reps or elevated)',
      'Minute 4: 12/10 Cal Row (scale: 10/8 Cal)',
    ],
    notes: 'Shoulder strength + conditioning',
  },
  {
    name: 'Core Crusher',
    type: 'EMOM',
    duration: 40,
    description: 'Core-focused + conditioning',
    movements: [
      'Minute 1: 12 GHD Sit-ups (scale: 15 abmat sit-ups)',
      'Minute 2: 10 Toes-to-Bar (scale: knee raises)',
      'Minute 3: 20 Russian Twists (scale: bodyweight)',
      'Minute 4: 10/8 Cal Bike (scale: 8/6 Cal)',
    ],
    notes: 'Core-focused + conditioning',
  },
  {
    name: 'Barbell Beast',
    type: 'EMOM',
    duration: 40,
    description: 'Heavy barbell complex',
    movements: [
      'Minute 1: 4 Deadlifts (125/84 kg; scale: 102/70 kg)',
      'Minute 2: 4 Power Cleans (84/57 kg; scale: 61/43 kg)',
      'Minute 3: 4 Front Squats (70/48 kg; scale: 52/34 kg)',
      'Minute 4: 4 Push Jerks (61/43 kg; scale: 43/29 kg)',
    ],
    notes: 'Heavy barbell complex',
  },
  {
    name: 'The Grinder 2.0',
    type: 'EMOM',
    duration: 40,
    description: 'High-volume grinder',
    movements: [
      'Minute 1: 10 Burpee Box Jump Overs (61/51 cm; scale: step-overs)',
      'Minute 2: 10 Hang Power Cleans (52/34 kg; scale: 43/29 kg)',
      'Minute 3: 15 Wall Balls (9/6 kg; scale: 6/5 kg)',
      'Minute 4: 15/12 Cal Row (scale: 12/10 Cal)',
    ],
    notes: 'High-volume grinder',
  },
  {
    name: 'Pull-Push Power',
    type: 'EMOM',
    duration: 40,
    description: 'Upper body balanced + conditioning',
    movements: [
      'Minute 1: 8 Pull-ups (scale: banded or ring rows)',
      'Minute 2: 10 Push-ups (scale: knee or incline)',
      'Minute 3: 12 KB Swings (32/24 kg; scale: 24/16 kg)',
      'Minute 4: 12/10 Cal Ski (scale: 10/8 Cal or 200/150 m)',
    ],
    notes: 'Upper body balanced + conditioning',
  },
  {
    name: 'Iron Flow',
    type: 'EMOM',
    duration: 40,
    description: 'Barbell + gymnastics flow',
    movements: [
      'Minute 1: 5 Squat Cleans (70/48 kg; scale: 52/34 kg)',
      'Minute 2: 8 Shoulder-to-Overhead (61/43 kg; scale: 43/29 kg)',
      'Minute 3: 10 Toes-to-Bar (scale: knee raises)',
      'Minute 4: 12/10 Cal Bike (scale: 10/8 Cal)',
    ],
    notes: 'Barbell + gymnastics flow',
  },
  {
    name: 'DT Reloaded',
    type: 'EMOM',
    duration: 40,
    description: 'DT-style EMOM',
    movements: [
      'Minute 1: 12 Deadlifts (70/48 kg; scale: 52/34 kg)',
      'Minute 2: 9 Hang Cleans (70/48 kg; scale: 52/34 kg)',
      'Minute 3: 6 Push Jerks (70/48 kg; scale: 52/34 kg)',
      'Minute 4: 12/10 Cal Row (scale: 10/8 Cal)',
    ],
    notes: 'DT-style EMOM',
  },
  {
    name: 'Sweat Factory',
    type: 'EMOM',
    duration: 40,
    description: 'High-intensity conditioning',
    movements: [
      'Minute 1: 12 Wall Balls (9/6 kg; scale: 6/5 kg)',
      'Minute 2: 12 Kettlebell Swings (32/24 kg; scale: 24/16 kg)',
      'Minute 3: 12/10 Cal Ski (scale: 10/8 Cal)',
      'Minute 4: 12/10 Cal Bike (scale: 10/8 Cal)',
    ],
    notes: 'High-intensity conditioning',
  },
  {
    name: 'Barbell + Gymnastics',
    type: 'EMOM',
    duration: 40,
    description: 'Barbell + gymnastics combo',
    movements: [
      'Minute 1: 3 Snatches (52/34 kg; scale: 43/29 kg)',
      'Minute 2: 8 Toes-to-Bar (scale: hanging knee raises)',
      'Minute 3: 10 Box Jumps (61/51 cm; scale: 51/41 cm)',
      'Minute 4: 15/12 Cal Row (scale: 12/10 Cal)',
    ],
    notes: 'Barbell + gymnastics combo',
  },
  {
    name: 'Posterior Chain Party',
    type: 'EMOM',
    duration: 40,
    description: 'Posterior chain focus',
    movements: [
      'Minute 1: 6 Deadlifts (102/70 kg; scale: 84/57 kg)',
      'Minute 2: 10 Hip Extensions (scale: good mornings)',
      'Minute 3: 12 GHD Sit-ups (scale: abmat)',
      'Minute 4: 15/12 Cal Bike (scale: 12/10 Cal)',
    ],
    notes: 'Posterior chain focus',
  },
  {
    name: 'Fight for 40',
    type: 'EMOM',
    duration: 40,
    description: 'Full-body fight',
    movements: [
      'Minute 1: 12/10 Cal Row (scale: 10/8 Cal)',
      'Minute 2: 8 Thrusters (43/29 kg; scale: 34/25 kg)',
      'Minute 3: 10 Pull-ups (scale: jumping pull-ups)',
      'Minute 4: 8 Bar-Facing Burpees (scale: step-overs)',
    ],
    notes: 'Full-body fight',
  },
];

/**
 * Get random WODs to include in AI prompt
 */
export const getRandomWODExamples = (count: number = 3): CrossFitWOD[] => {
  const shuffled = [...crossfitWODs].sort(() => 0.5 - Math.random());
  const selected = shuffled.slice(0, count);
  
  // Log which WODs were selected for AI inspiration
  console.log('📚 WOD Examples selected for AI:', selected.map(w => w.name).join(', '));
  
  return selected;
};

/**
 * Format WOD for AI prompt
 */
export const formatWODForPrompt = (wod: CrossFitWOD): string => {
  return `
WOD: "${wod.name}" (${wod.type})
${wod.duration ? `Duration: ${wod.duration} minutes` : ''}
Description: ${wod.description}
Movements:
${wod.movements.map(m => `- ${m}`).join('\n')}
${wod.notes ? `Notes: ${wod.notes}` : ''}
`.trim();
};

/**
 * Get formatted WOD examples for AI
 */
export const getWODExamplesForAI = (): string => {
  const examples = getRandomWODExamples(4);
  return examples.map(formatWODForPrompt).join('\n\n---\n\n');
};

